import {test,expect} from './support/fixtures';
import {setup} from './support/ui';
test('assistente: conta, múltiplos destinos, resumo e edição aprovada',async({page})=>{
 await setup(page);await page.getByRole('button',{name:'Abrir assistente Atlinhas',exact:true}).click();
 await page.getByRole('button',{name:'Verificações',exact:true}).click();
 const panel=page.getByLabel('Preparar verificações',{exact:true});
 await panel.getByRole('button',{name:'Consultar contas e vínculos',exact:true}).click();
 await panel.getByRole('button',{name:'Nova conta de verificação',exact:true}).click();
 await panel.getByRole('button',{name:'Preparar resumo das verificações',exact:true}).click();
 await expect(panel.getByRole('log')).toContainText('Qual é o serviço?');
 await panel.getByLabel('Serviço',{exact:true}).fill('Serviço teste');await panel.getByLabel('Nome da conta',{exact:true}).fill('Conta teste');await panel.getByLabel('Login',{exact:true}).fill('usuario@example.invalid');
 await panel.getByRole('button',{name:'Adicionar método',exact:true}).click();
 await panel.getByLabel('Método de confirmação',{exact:true}).selectOption('key');
 await panel.getByLabel('Identificação ou local, sem códigos',{exact:true}).fill('Chave da administração');
 await panel.getByRole('button',{name:'Adicionar destino',exact:true}).click();
 await panel.getByLabel('Identificação ou local, sem códigos',{exact:true}).nth(1).fill('Chave da TI');
 await panel.getByRole('button',{name:'Preparar resumo das verificações',exact:true}).click();
 const review=panel.getByLabel('Resumo das verificações',{exact:true});
 await expect(review).toContainText('Chave da administração');await expect(review).toContainText('Chave da TI');await expect(review).toContainText('Não conferida');
 expect((await (await page.request.get('/api/access')).json()).accounts).toHaveLength(0);
 await panel.getByLabel('Nome da conta',{exact:true}).fill('Conta corrigida');await expect(review).toHaveCount(0);
 await panel.getByRole('button',{name:'Preparar resumo das verificações',exact:true}).click();await expect(review).toContainText('Conta corrigida');
 await page.setViewportSize({width:390,height:800});await panel.getByRole('button',{name:'Aprovar e salvar verificação',exact:true}).click();
 await expect(panel.getByRole('log')).toContainText('Conta salva após sua aprovação');
 const saved=(await (await page.request.get('/api/access')).json()).accounts[0];expect(saved.methods[0].destinations).toHaveLength(2);expect(saved.policy.visibility).toBe('selected');
 await panel.getByRole('button',{name:'Consultar contas e vínculos',exact:true}).click();await panel.getByRole('button',{name:'Editar Conta corrigida · usuario@example.invalid',exact:true}).click();
 await panel.getByLabel('Verificação em duas etapas',{exact:true}).selectOption('enabled');
 await panel.getByRole('button',{name:'Preparar resumo das verificações',exact:true}).click();await expect(review).toContainText('Antes: Não conferida');await expect(review).toContainText('Depois: Ativada');
 await panel.getByRole('button',{name:'Aprovar e salvar verificação',exact:true}).click();await expect(panel.getByRole('log')).toContainText('Conta salva após sua aprovação');
 expect((await (await page.request.get('/api/access')).json()).accounts[0].mfa).toBe('enabled');
});
