import {test, expect} from './support/fixtures';
import {setup, newLine, saveLine, settings, dashboard, choose, saveDevice, card, openLine} from './support/ui';

test('regressão 1–4: cadastro de aparelho, múltiplos eSIMs, GB, movimentação, histórico e persistência', async ({page, app}) => {
  await setup(page);
  await expect(page.getByText('Tudo pronto para organizar suas linhas', {exact: true})).toBeVisible();
  await expect(page.getByRole('button', {name: /Usar com meus dados|Ver demonstração/})).toHaveCount(0);
  await expect(page.locator('.agent-card')).toHaveCount(0);
  await settings(page); await page.getByRole('button', {name: 'Novo aparelho', exact: true}).click();
  await page.getByLabel('iPhone', {exact: true}).check();
  await choose(page, 'Modelo', 'iPhone 15');
  await page.getByLabel('Nome do aparelho', {exact: true}).fill('Telefone de teste');
  await page.getByLabel('Local do aparelho', {exact: true}).fill('Sala de testes');
  await page.getByRole('checkbox', {name: 'eSIM 1', exact: true}).check();
  await page.getByRole('button', {name: 'Adicionar eSIM', exact: true}).click();
  await expect(page.getByRole('checkbox', {name: 'eSIM 2', exact: true})).toBeChecked();
  await saveDevice(page); await dashboard(page);
  for (const [name, number, slot] of [['Linha eSIM um', '51911110001', 'eSIM 1'], ['Linha eSIM dois', '51911110002', 'eSIM 2']]) {
    await newLine(page, name, number);
    await choose(page, 'Aparelho vinculado', 'Telefone de teste · iPhone 15');
    await choose(page, 'Slot do chip', slot);
    await page.getByLabel('Pacote de dados ativo em GB', {exact: true}).fill('25');
    await saveLine(page);
    await expect(card(page, name)).toContainText('iPhone 15 · ' + slot);
    await expect(card(page, name)).toContainText('25 GB');
  }
  await settings(page); await page.getByRole('button', {name: /Telefone de teste/}).click();
  await page.getByLabel('Local do aparelho', {exact: true}).fill('Armário de testes'); await saveDevice(page);
  await dashboard(page); await expect(card(page, 'Linha eSIM um')).toContainText('Armário de testes');
  await page.getByRole('button', {name: 'Histórico de Linha eSIM um', exact: true}).click();
  await expect(page.locator('.audit-timeline article').first()).toContainText('Aparelho atualizado');
  await expect(page.locator('.audit-timeline article').first()).toContainText('Sala de testes');
  await page.keyboard.press('Escape');
  await openLine(page, 'Linha eSIM um');
  await expect(page.getByLabel('Pacote de dados ativo em GB', {exact: true})).toHaveValue('25');
  await page.getByLabel('Pacote de dados ativo em GB', {exact: true}).fill('2,5'); await saveLine(page);
  await page.getByRole('button', {name: 'Histórico de Linha eSIM um', exact: true}).click();
  await expect(page.locator('.audit-timeline article').first()).toContainText('25 GB');
  await expect(page.locator('.audit-timeline article').first()).toContainText('2,5 GB');
  const eventCount = await page.locator('.audit-timeline article').count();
  await page.keyboard.press('Escape'); await openLine(page, 'Linha eSIM um'); await saveLine(page);
  await page.getByRole('button', {name: 'Histórico de Linha eSIM um', exact: true}).click();
  await expect(page.locator('.audit-timeline article')).toHaveCount(eventCount);
  await page.keyboard.press('Escape');
  await app.restart(); await page.reload();
  await expect(card(page, 'Linha eSIM um')).toContainText('2,5 GB');
  await expect(card(page, 'Linha eSIM dois')).toContainText('iPhone 15 · eSIM 2');
});

test('regressão 3 e 8: filtros, indicadores globais, pendências e hover de 2,5%', async ({page}) => {
  await setup(page); await newLine(page, 'Operação de teste');
  await page.getByLabel('Mensalidade', {exact: true}).fill('45'); await saveLine(page);
  await newLine(page, 'Reserva de teste', '51911110002');
  await choose(page, 'Situação', 'Em reserva');
  await choose(page, 'Operadora', 'Claro');
  await page.getByLabel('Responsável', {exact: true}).fill('');
  await page.getByLabel('Onde está guardado?', {exact: true}).fill('');
  await page.getByLabel('Mensalidade', {exact: true}).fill('20'); await saveLine(page);
  await expect(page.locator('.agent-card')).toContainText('1 linha');
  const metrics = page.locator('.metrics');
  await expect(metrics).toContainText('65,00');
  await page.getByLabel('Buscar linhas', {exact: true}).fill('Operação');
  await expect(page.locator('.line-card-wrap')).toHaveCount(1); await expect(metrics).toContainText('65,00');
  await page.getByRole('button', {name: 'Limpar filtros', exact: true}).click();
  await choose(page, 'Filtrar por operadora', 'Claro');
  await expect(card(page, 'Reserva de teste')).toBeVisible(); await expect(page.locator('.line-card-wrap')).toHaveCount(1);
  await page.getByRole('button', {name: 'Limpar filtros', exact: true}).click();
  await page.locator('.agent-card').getByRole('button').click();
  await expect(card(page, 'Reserva de teste')).toBeVisible(); await expect(page.locator('.line-card-wrap')).toHaveCount(1);
  await openLine(page, 'Reserva de teste');
  await page.getByLabel('Responsável', {exact: true}).fill('Responsável de teste');
  await page.getByLabel('Onde está guardado?', {exact: true}).fill('Gaveta 2'); await saveLine(page);
  await expect(page.locator('.agent-card')).toHaveCount(0);
  await page.getByRole('button', {name: 'Limpar filtros', exact: true}).click();
  const target = card(page, 'Operação de teste');
  const before = await target.locator('.overview-line-card').evaluate(el => ({background: getComputedStyle(el).backgroundColor, color: getComputedStyle(el).color}));
  await target.hover();
  await expect(target).toHaveCSS('transform', 'matrix(1.025, 0, 0, 1.025, 0, 0)');
  const after = await target.locator('.overview-line-card').evaluate(el => ({background: getComputedStyle(el).backgroundColor, color: getComputedStyle(el).color}));
  expect(after).toEqual(before);
  await metrics.locator('.metric').first().hover();
  await expect(metrics.locator('.metric').first()).toHaveCSS('transform', 'matrix(1.025, 0, 0, 1.025, 0, 0)');
  await page.emulateMedia({reducedMotion: 'reduce'}); await target.hover();
  await expect(target).toHaveCSS('transform', 'none');
  await page.setViewportSize({width: 390, height: 844});
  await expect(page.getByRole('heading', {name: 'Controle de linhas.'})).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBeTruthy();
});

test('regressão 5: número duplicado e edição simultânea não sobrescrevem o cadastro', async ({page, context}) => {
  await setup(page); await newLine(page, 'Linha original'); await saveLine(page);
  await newLine(page, 'Duplicada');
  await page.getByRole('button', {name: 'Salvar linha', exact: true}).click();
  await expect(page.getByText(/Este número já está cadastrado/)).toBeVisible();
  await page.keyboard.press('Escape'); await expect(page.locator('.line-card-wrap')).toHaveCount(1);
  const other = await context.newPage(); await other.goto('/');
  await openLine(other, 'Linha original'); await openLine(page, 'Linha original');
  await page.getByLabel('Identificação da linha', {exact: true}).fill('Alteração mais recente'); await saveLine(page);
  await other.getByLabel('Identificação da linha', {exact: true}).fill('Alteração antiga');
  const response = other.waitForResponse(r => r.url().endsWith('/api/lines') && r.request().method() === 'POST');
  await other.getByRole('button', {name: 'Salvar linha', exact: true}).click();
  expect((await response).status()).toBe(409);
  await expect(other.getByRole('dialog')).toBeVisible();
  await page.reload(); await expect(card(page, 'Alteração mais recente')).toBeVisible();
  await expect(card(page, 'Alteração antiga')).toHaveCount(0);
});
