'use client';
import {useCallback,useEffect,useMemo,useRef,useState,type FormEvent,type ReactNode} from 'react';
import {Search,Plus,KeyRound,LockKeyhole,Eye,EyeOff,Copy,Flag,ArrowLeft,ArrowUpRight,Check,History,Smartphone,Mail,MessageSquare,LoaderCircle,Trash2} from 'lucide-react';
import {toast} from 'sonner';
import {Button} from '@/components/ui/button';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {accountDataSchema,newAccount,defaultPolicy,methodLabels,mfaLabels,accountAttention,destinationInfo,type AccessDirectory,type AccessAccount,type AccountData,type AccountPolicy,type VerificationMethod,type Destination,type AccessEvent} from '@/lib/accounts';
import {clientId} from '@/lib/client-id';
import {displayNumber,type Config,type Line} from '@/lib/atlas';
import type {Actor} from '@/lib/access';
import './access.css';
async function call<T>(path:string,body?:unknown):Promise<T>{const r=await fetch('/api/'+path,{...(body===undefined?{cache:'no-store'}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});const data=await r.json() as T&{error?:string};if(!r.ok)throw Error(data.error||'Não foi possível concluir.');return data}
const emptyDirectory:AccessDirectory={accounts:[],people:[],users:[],reports:[],canManage:false};
function useDirectory(){const [data,setData]=useState(emptyDirectory),[loading,setLoading]=useState(true),[error,setError]=useState('');const refresh=useCallback(async()=>{setError('');try{const next=await call<AccessDirectory>('access');setData(next);return next}catch(e){setError((e as Error).message);return null}finally{setLoading(false)}},[]);useEffect(()=>{void refresh()},[refresh]);return {data,loading,error,refresh};}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="access-field"><span>{label}</span>{children}</label>}
function ErrorBox({message}:{message:string}){return message?<p className="access-notice danger" role="alert">{message}</p>:null}
const personName=(id:string|null,data:AccessDirectory)=>data.people.find(p=>p.id===id)?.name||'A definir';
const actions:Record<string,string>={'account-created':'Conta cadastrada','account-updated':'Cadastro atualizado',checked:'Cadastro conferido','problem-reported':'Problema informado','problem-resolved':'Pendência resolvida','vault-unlocked':'Cofre desbloqueado','secret-revealed':'Credencial visualizada','secret-copy-requested':'Credencial solicitada para cópia','secret-updated':'Credencial alterada','backup-restored':'Conta recuperada do backup'};
const methodName=(m:VerificationMethod)=>methodLabels[m.type];
function Status({account,config,lines,data}:{account:AccessAccount;config:Config;lines:Line[];data:AccessDirectory}){const a=accountAttention(account,config,lines,data.accounts,data.people);return <span className={'access-badge '+(a.blocked?'danger':a.protection.length||a.pending.length?'warning':'')}>{account.archived?'Arquivada':a.blocked?'Acesso impedido':a.protection[0]||a.pending[0]||'Cadastro conferido'}</span>}
export default function AccessPanel({config,lines,user,mode='accounts',initialId,onVault}:{config:Config;lines:Line[];user:Actor;mode?:'accounts'|'vault';initialId?:string;onVault:(id:string)=>void}){
 const {data,loading,error,refresh}=useDirectory();const [selected,setSelected]=useState(initialId||''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[editing,setEditing]=useState<AccessAccount|'new'|null>(null),[secret,setSecret]=useState<string|null>(null);
 const visible=useMemo(()=>data.accounts.filter(a=>{const attention=accountAttention(a,config,lines,data.accounts,data.people);if(filter==='archived'?!a.archived:a.archived)return false;if(filter==='blocked'&&!attention.blocked)return false;if(filter==='review'&&!attention.protection.length&&!attention.pending.length&&!data.reports.some(r=>r.accountId===a.id&&r.status==='open'))return false;const refs=a.methods.flatMap(m=>m.destinations.map(t=>{const d=destinationInfo(t,config,lines,data.accounts,data.people);return [d.label,d.owner,d.device?.name].join(' ')})).join(' ');return [a.service,a.label,a.login,personName(a.ownerId,data),refs].join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase())}),[data,config,lines,query,filter]);
 const active=visible.find(a=>a.id===selected)||(!selected?undefined:visible[0]);useEffect(()=>{if(initialId)setSelected(initialId)},[initialId]);useEffect(()=>{if(!selected&&visible.length&&window.innerWidth>760)setSelected(visible[0].id)},[visible,selected]);
 const aSecret=data.accounts.find(a=>a.id===secret);
 async function saved(){setEditing(null);await refresh()}
 return <section className="access-module"><div className="access-toolbar"><label className="access-search"><Search size={18}/><input aria-label="Buscar contas" placeholder="Conta, e-mail, pessoa ou aparelho…" value={query} onChange={e=>setQuery(e.target.value)}/></label>{data.canManage&&<Button onClick={()=>setEditing('new')}><Plus/>Nova conta</Button>}</div><div className="access-filters">{[['all','Todas'],['blocked','Acesso impedido'],['review','Precisa de revisão'],['archived','Arquivadas']].map(([key,label])=><button key={key} type="button" aria-pressed={filter===key} onClick={()=>{setFilter(key);setSelected('')}}>{label}</button>)}</div><ErrorBox message={error}/>{loading?<p role="status"><LoaderCircle className="spin"/>Carregando contas…</p>:<div className={'access-layout '+(active?'has-selection':'')}><div className="access-list" aria-label="Contas cadastradas">{visible.map(a=><button type="button" className="access-account" key={a.id} aria-pressed={active?.id===a.id} onClick={()=>setSelected(a.id)}><strong>{a.label}</strong><small>{a.login}</small><Status account={a} config={config} lines={lines} data={data}/></button>)}{!visible.length&&<div className="access-empty"><KeyRound/><h2>{data.accounts.length?'Nenhuma conta encontrada':'Onde chegam as confirmações?'}</h2><p>{data.accounts.length?'Ajuste a busca ou os filtros.':data.canManage?'Cadastre a primeira conta e vincule seus números, e-mails e aparelhos.':'O administrador ainda não cadastrou contas disponíveis para seu usuário.'}</p></div>}</div>{active?<div className="access-detail"><button className="access-mobile-back" type="button" onClick={()=>setSelected('')}><ArrowLeft size={16}/>Voltar às contas</button>{mode==='vault'?<CredentialPanel key={active.id+'-'+active.version} account={active} scope="vault" onVault={onVault} onSaved={refresh}/>:<AccountView key={active.id+'-'+active.version} account={active} data={data} config={config} lines={lines} onSelect={setSelected} onSecret={()=>setSecret(active.id)} onEdit={()=>setEditing(active)} refresh={refresh}/>}</div>:visible.length>0&&<div className="access-empty access-choose"><h2>Selecione uma conta</h2><p>Veja o destino da confirmação e o responsável.</p></div>}</div>}
 <p className="access-caption">Destinos informados pela equipe. O Atlas não recebe nem monitora códigos nesta versão.</p>
 <Sheet open={!!editing} onOpenChange={open=>{if(!open)setEditing(null)}}><SheetContent className="line-sheet access-editor-sheet"><SheetHeader><SheetTitle>{editing==='new'?'Nova conta':'Editar conta'}</SheetTitle><SheetDescription>Comece pelos dados essenciais. Adicione os métodos conforme conferir os acessos.</SheetDescription></SheetHeader>{editing&&<AccountEditor key={editing==='new'?'new':editing.id} account={editing==='new'?undefined:editing} data={data} config={config} lines={lines} user={user} onSaved={saved} refresh={refresh}/>}</SheetContent></Sheet>
 <Sheet open={!!aSecret} onOpenChange={open=>{if(!open)setSecret(null)}}><SheetContent className="line-sheet"><SheetHeader><SheetTitle>Credencial</SheetTitle><SheetDescription>Acesso rápido à conta selecionada.</SheetDescription></SheetHeader>{aSecret&&<CredentialPanel key={aSecret.id+'-'+aSecret.version} account={aSecret} scope="quick" onVault={id=>{setSecret(null);onVault(id)}} onSaved={refresh}/>}</SheetContent></Sheet>
 </section>;
}
function AccountView({account:a,data,config,lines,onSelect,onSecret,onEdit,refresh}:{account:AccessAccount;data:AccessDirectory;config:Config;lines:Line[];onSelect:(id:string)=>void;onSecret:()=>void;onEdit?:()=>void;refresh:()=>Promise<unknown>}){
 const [reporting,setReporting]=useState(false),[reason,setReason]=useState(''),[destination,setDestination]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[history,setHistory]=useState<AccessEvent[]|null>(null);
 const attention=accountAttention(a,config,lines,data.accounts,data.people),access=a.methods.filter(m=>m.purpose!=='recovery'),stages=[...new Set(access.map(m=>m.stage))].sort((x,y)=>x-y),recovery=a.methods.filter(m=>m.purpose!=='access'),openReports=data.reports.filter(r=>r.accountId===a.id&&r.status==='open');
 async function act(body:unknown){setBusy(true);setError('');try{await call('access',body);await refresh();setHistory(null);setReporting(false);toast.success('Registro salvo.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function destinations(m:VerificationMethod){return <div className="access-destinations">{m.destinations.map(t=>{const d=destinationInfo(t,config,lines,data.accounts,data.people),report=openReports.some(r=>r.destinationId===t.id);return <div className="access-destination" key={t.id}>{t.lineId?<MessageSquare/>:t.accountId?<Mail/>:<Smartphone/>}<div><strong>{t.lineId?displayNumber(d.label):d.label}</strong><p>{d.owner||'Responsável a definir'}{d.device&&(t.lineId||t.accountId)?' · '+d.device.name:''}{d.line?.slot?' · '+(d.line.slot==='eSIM'?'eSIM 1':d.line.slot):''}</p>{t.description&&t.description!==d.label&&<small>{t.description}</small>}{d.device?.location&&<small>{d.device.location}</small>}<small className={d.unavailable?'access-danger':''}>{d.unavailable?'Sem acesso informado':report?'Problema informado · precisa conferir':t.state==='unknown'?'Disponibilidade não conferida':'Disponível segundo o cadastro'}</small>{t.accountId&&d.mail&&<button type="button" className="access-text-button" onClick={()=>onSelect(t.accountId!)}>Consultar esta caixa de e-mail<ArrowUpRight size={14}/></button>}</div></div>})}</div>}
 function method(m:VerificationMethod,preferred=false){return <div className="access-method" key={m.id}><div className="access-method-heading"><strong>{methodName(m)}</strong>{preferred&&<small>Preferencial</small>}</div>{m.destinations.length>1&&<p className="access-method-help">Um dos destinos cadastrados pode ser usado para esta confirmação.</p>}{destinations(m)}{m.instruction&&<p className="access-method-help">{m.instruction}</p>}</div>}
 return <><div className="access-detail-heading"><span>{a.service}</span><h2>{a.label}</h2><p>{a.login}</p></div><div className="access-section-title"><h3>Onde confirmar</h3><small>Responsável: {personName(a.ownerId,data)}</small></div><ErrorBox message={error}/>{attention.blocked&&<p className="access-notice danger">Uma etapa obrigatória não tem destino acessível cadastrado. Confira com o responsável pela conta.</p>}{!access.length&&<p className="access-notice">Nenhum método de confirmação cadastrado. Isso não informa se a proteção está ativada no serviço.</p>}{stages.map(stage=>{const group=access.filter(m=>m.stage===stage),primary=group.find(m=>m.preferred)||group[0],alternatives=group.filter(m=>m.id!==primary.id);return <div key={stage}>{stages.length>1&&<h4 className="access-stage">Etapa {stage} · necessária</h4>}{method(primary,true)}{alternatives.length>0&&<details className="access-disclosure"><summary>Alternativas de confirmação · {alternatives.length}</summary>{alternatives.map(m=>method(m))}</details>}</div>})}{recovery.length>0&&<details className="access-disclosure"><summary>Recuperação da conta · {recovery.length}</summary>{recovery.map(m=>method(m))}</details>}
 {(attention.pending.length>0||attention.protection.length>0)&&<details className="access-disclosure"><summary className="access-warning">Proteção e cadastro · {attention.pending.length+attention.protection.length} pendência(s)</summary><ul>{[...attention.protection,...attention.pending].map(text=><li key={text}>{text}</li>)}</ul></details>}
 <div className="access-actions"><Button variant="outline" onClick={onSecret}><KeyRound/>Ver credencial</Button><Button variant="ghost" onClick={()=>setReporting(!reporting)}><Flag/>Informar problema</Button></div>
 {reporting&&<form className="access-form access-notice" onSubmit={e=>{e.preventDefault();void act({action:'report',id:a.id,destinationId:destination||null,reason})}}><Field label="Destino com problema"><select value={destination} onChange={e=>setDestination(e.target.value)}><option value="">Cadastro da conta</option>{a.methods.flatMap(m=>m.destinations.map(t=><option key={t.id} value={t.id}>{methodName(m)} · {destinationInfo(t,config,lines,data.accounts,data.people).label}</option>))}</select></Field><Field label="O que aconteceu? Não inclua senhas."><textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ex.: aparelho não está no local indicado."/></Field><p className="access-caption">O relato ficará pendente para {personName(a.ownerId,data)}. O destino não será alterado automaticamente.</p><Button disabled={busy} type="submit">Registrar problema</Button></form>}
 {openReports.length>0&&<div className="access-reports"><h4>Problemas informados</h4>{openReports.map(r=><div key={r.id}><p>{r.reason}</p><small>{r.author} · {new Date(r.createdAt).toLocaleString('pt-BR')}</small>{a.canEdit&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>void act({action:'resolve',id:r.id})}>Marcar resolvido</Button>}</div>)}</div>}
 <div className="access-management"><div className="access-section-title"><small>Verificação em duas etapas: {mfaLabels[a.mfa]}</small>{onEdit&&a.canEdit&&<button className="access-text-button" onClick={onEdit}>Editar cadastro</button>}</div><small>{a.checkedAt?'Conferido em '+new Date(a.checkedAt).toLocaleDateString('pt-BR'):'Conferência manual pendente'}</small>{a.canEdit&&<Button variant="ghost" size="sm" disabled={busy} onClick={()=>void act({action:'check',id:a.id,version:a.version})}><Check/>Conferi o cadastro</Button>}<details className="access-disclosure" onToggle={e=>{if(e.currentTarget.open&&history===null)void call<{history:AccessEvent[]}>('access?history='+encodeURIComponent(a.id)).then(d=>setHistory(d.history)).catch(e=>setError(e.message))}}><summary><History size={14}/> Histórico</summary>{history===null?<p>Carregando…</p>:history.map(h=><div className="access-event" key={h.id}><strong>{actions[h.action]||h.action}</strong><small>{h.actor} · {new Date(h.createdAt).toLocaleString('pt-BR')}</small>{h.action==='account-updated'&&<details><summary>Ver alteração do cadastro</summary>{Array.isArray(h.detail.changes)&&(h.detail.changes as {field:string;before:string;after:string}[]).map((c,i)=><div className="access-event" key={i}><strong>{c.field}</strong><p>Antes: {c.before}</p><p>Depois: {c.after}</p></div>)}{h.detail.policyChanged===true&&<p>Permissões desta conta atualizadas.</p>}</details>}</div>)}</details></div></>;
}
function AccountEditor({account,data,config,lines,user,onSaved,refresh}:{account?:AccessAccount;data:AccessDirectory;config:Config;lines:Line[];user:Actor;onSaved:()=>Promise<unknown>;refresh:()=>Promise<AccessDirectory|null>}){
 const [form,setForm]=useState<AccountData>(()=>account?accountDataSchema.parse(Object.fromEntries(Object.keys(newAccount(null)).map(k=>[k,account[k as keyof AccessAccount]]))):newAccount(data.people.find(p=>p.userId===user.id)?.id||null));
 const [policy,setPolicy]=useState<AccountPolicy>(account?.policy||defaultPolicy),[busy,setBusy]=useState(false),[error,setError]=useState(''),[newPerson,setNewPerson]=useState('');
 const change=<K extends keyof AccountData>(key:K,value:AccountData[K])=>setForm(old=>({...old,[key]:value}));
 function updateMethod(index:number,next:VerificationMethod){setForm(old=>({...old,methods:old.methods.map((m,i)=>i===index?next:next.preferred&&m.stage===next.stage&&next.purpose!=='recovery'?{...m,preferred:false}:m)}))}
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await call('access',{action:'save',...(account?{id:account.id}:{}),version:account?.version||0,data:form,...(data.canManage?{policy}:{})});toast.success('Conta salva.');await onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function addPerson(){setBusy(true);setError('');try{const result=await call<{person:{id:string}}>('access',{action:'person',name:newPerson});await refresh();change('ownerId',result.person.id);setNewPerson('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <form className="access-module access-form" onSubmit={submit}><fieldset disabled={busy}><Field label="Serviço"><input required maxLength={200} value={form.service} placeholder="Ex.: Google, ChatGPT, Meta" onChange={e=>change('service',e.target.value)}/></Field><Field label="Nome da conta"><input required maxLength={200} value={form.label} placeholder="Ex.: Google · Administração" onChange={e=>change('label',e.target.value)}/></Field><Field label="Login ou e-mail"><input required maxLength={200} autoComplete="off" value={form.login} onChange={e=>change('login',e.target.value)}/></Field><label className="access-check"><input type="checkbox" checked={form.kind==='email'} onChange={e=>change('kind',e.target.checked?'email':'service')}/>Esta conta é uma caixa de e-mail</label><Field label="Responsável pela conferência"><select value={form.ownerId||''} onChange={e=>change('ownerId',e.target.value||null)}><option value="">Definir depois</option>{data.people.map(p=><option key={p.id} value={p.id}>{p.name}{p.userId?' · usuário Atlas':''}</option>)}</select></Field>{data.canManage&&<details className="access-disclosure"><summary>Cadastrar outra pessoa</summary><div className="access-toolbar"><input aria-label="Nome do novo responsável" maxLength={200} value={newPerson} onChange={e=>setNewPerson(e.target.value)} placeholder="Nome da pessoa"/><Button type="button" disabled={!newPerson.trim()} onClick={()=>void addPerson()}>Adicionar</Button></div><small>Cadastrar uma pessoa não cria login nem concede acesso às senhas.</small></details>}<Field label="Verificação em duas etapas"><select value={form.mfa} onChange={e=>change('mfa',e.target.value as AccountData['mfa'])}>{Object.entries(mfaLabels).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></Field><p className="access-caption">Cadastrar um método não ativa a proteção no serviço.</p>
 <div className="access-section-title"><h3>Confirmação e recuperação</h3><Button size="sm" type="button" variant="outline" onClick={()=>change('methods',[...form.methods,{id:clientId(),type:'sms',purpose:'access',stage:1,preferred:!form.methods.some(m=>m.preferred&&m.purpose!=='recovery'),instruction:'',destinations:[blankDestination()]}])}><Plus/>Adicionar método</Button></div>{!form.methods.length&&<p className="access-notice">Você pode salvar agora e cadastrar os destinos depois.</p>}{form.methods.map((m,i)=><MethodEditor key={m.id} method={m} config={config} lines={lines} data={data} accountId={account?.id} onChange={next=>updateMethod(i,next)} onRemove={()=>change('methods',form.methods.filter((_,j)=>i!==j))}/>)}
 <details className="access-disclosure"><summary>Mais informações</summary><Field label="Setor"><input maxLength={200} value={form.sector} onChange={e=>change('sector',e.target.value)}/></Field>{account&&<label className="access-check"><input type="checkbox" checked={form.archived} onChange={e=>change('archived',e.target.checked)}/>Arquivar conta, preservando vínculos e histórico</label>}</details>
 {data.canManage&&<details className="access-disclosure"><summary>Permissões desta conta e credencial</summary><Field label="Quem vê a conta"><select value={policy.visibility} onChange={e=>setPolicy(p=>({...p,visibility:e.target.value as AccountPolicy['visibility']}))}><option value="team">Equipe autorizada no Atlas</option><option value="selected">Somente administrador e pessoas selecionadas</option></select></Field><label className="access-check"><input type="checkbox" checked={policy.sensitive} onChange={e=>setPolicy(p=>({...p,sensitive:e.target.checked,quickAccess:e.target.checked?false:p.quickAccess}))}/>Credencial sensível</label><label className="access-check"><input type="checkbox" checked={policy.quickAccess} onChange={e=>setPolicy(p=>({...p,quickAccess:e.target.checked}))}/>Permitir consulta fora do Cofre, para usuários autorizados</label><p className="access-caption">O administrador gerencia os acessos. Revele, copie e edite somente após desbloquear com sua senha do Atlas.</p>{data.users.filter(u=>u.id!==user.id).map(u=><div className="access-permission-person" key={u.id}><strong>{u.name}{!u.active?' · bloqueado':''}</strong>{(['viewers','revealUsers','editUsers'] as const).map((field,i)=><label className="access-check" key={field}><input type="checkbox" checked={policy[field].includes(u.id)} onChange={e=>setPolicy(p=>({...p,[field]:e.target.checked?[...p[field],u.id]:p[field].filter(v=>v!==u.id)}))}/>{['Consultar a conta','Revelar e copiar credenciais','Editar cadastro e credenciais'][i]}</label>)}</div>)}</details>}
 <ErrorBox message={error}/><div className="access-actions"><Button type="submit" disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Check/>}Salvar conta</Button></div></fieldset></form>;
}
function blankDestination():Destination{return {id:clientId(),lineId:null,deviceId:null,accountId:null,personId:null,description:'',state:'unknown'}}
function MethodEditor({method:m,config,lines,data,accountId,onChange,onRemove}:{method:VerificationMethod;config:Config;lines:Line[];data:AccessDirectory;accountId?:string;onChange:(m:VerificationMethod)=>void;onRemove:()=>void}){
 const set=<K extends keyof VerificationMethod>(key:K,value:VerificationMethod[K])=>onChange({...m,[key]:value});
 const update=(index:number,next:Destination)=>set('destinations',m.destinations.map((t,i)=>i===index?next:t));
 return <details className="access-method-editor" open><summary>{methodName(m)} · {m.destinations.length} destino(s)</summary><div className="access-form"><Field label="Tipo de método"><select value={m.type} onChange={e=>{const type=e.target.value as VerificationMethod['type'];onChange({...m,type,purpose:type==='recovery'?'recovery':m.purpose,destinations:[blankDestination()]})}}>{Object.entries(methodLabels).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></Field><Field label="Finalidade"><select value={m.purpose} onChange={e=>set('purpose',e.target.value as VerificationMethod['purpose'])}>{m.type!=='recovery'&&<option value="access">Confirmação de acesso</option>}<option value="recovery">Recuperação da conta</option>{m.type!=='recovery'&&<option value="both">Acesso e recuperação</option>}</select></Field>
 {m.destinations.map((t,i)=><div className="access-destination-editor" key={t.id}><div className="access-section-title"><strong>Destino {i+1}</strong>{m.destinations.length>1&&<button type="button" aria-label={`Remover destino ${i+1}`} onClick={()=>set('destinations',m.destinations.filter((_,j)=>i!==j))}><Trash2 size={16}/></button>}</div>{['sms','call'].includes(m.type)?<Field label="Linha cadastrada"><select required value={t.lineId||''} onChange={e=>update(i,{...t,lineId:e.target.value||null})}><option value="">Selecione a linha</option>{lines.map(l=><option value={l.id} key={l.id}>{displayNumber(l.number)} · {l.name}</option>)}</select></Field>:m.type==='email'?<Field label="Caixa de e-mail cadastrada"><select required value={t.accountId||''} onChange={e=>update(i,{...t,accountId:e.target.value||null})}><option value="">Selecione a caixa</option>{data.accounts.filter(a=>a.kind==='email'&&a.id!==accountId).map(a=><option key={a.id} value={a.id}>{a.label} · {a.login}</option>)}</select><small>Se não aparecer, cadastre a caixa como uma conta de e-mail primeiro.</small></Field>:['prompt','authenticator','passkey'].includes(m.type)?<Field label="Aparelho cadastrado"><select required={m.type!=='passkey'} value={t.deviceId||''} onChange={e=>update(i,{...t,deviceId:e.target.value||null})}><option value="">{m.type==='passkey'?'Outra localização':'Selecione o aparelho'}</option>{config.devices.map(d=><option value={d.id} key={d.id}>{d.name} · {d.model}</option>)}</select></Field>:null}
 {(!['sms','call','email','prompt','authenticator'].includes(m.type))&&<Field label="Identificação ou localização"><input required={!t.deviceId} maxLength={500} placeholder="Sem senhas, códigos ou chaves secretas" value={t.description} onChange={e=>update(i,{...t,description:e.target.value})}/></Field>}<Field label="Quem recebe ou aprova"><select value={t.personId||''} onChange={e=>update(i,{...t,personId:e.target.value||null})}><option value="">Usar responsável da linha ou aparelho</option>{data.people.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></Field><Field label="Situação informada"><select value={t.state} onChange={e=>update(i,{...t,state:e.target.value as Destination['state']})}><option value="unknown">Precisa conferir</option><option value="available">Disponível</option><option value="unavailable">Sem acesso</option></select></Field></div>)}
 <Button variant="outline" type="button" onClick={()=>set('destinations',[...m.destinations,blankDestination()])}><Plus/>Adicionar outro destino</Button><Field label="Orientação para a equipe"><textarea maxLength={1000} placeholder="Ex.: abrir o aplicativo Google no aparelho indicado." value={m.instruction} onChange={e=>set('instruction',e.target.value)}/></Field>{m.purpose!=='recovery'&&<label className="access-check"><input type="checkbox" checked={m.preferred} onChange={e=>set('preferred',e.target.checked)}/>Caminho preferencial nesta etapa</label>}<details className="access-disclosure"><summary>Etapas obrigatórias</summary><Field label="Etapa"><input type="number" min={1} max={10} value={m.stage} onChange={e=>set('stage',Number(e.target.value))}/></Field><small>Métodos na mesma etapa são alternativas. Etapas diferentes são necessárias em sequência.</small></details><Button variant="ghost" type="button" onClick={onRemove}><Trash2/>Remover método</Button></div></details>;
}
type Unlock={token:string;expiresAt:number;purpose:'read'|'write'};
export function CredentialPanel({account:a,scope,onVault,onSaved}:{account:AccessAccount;scope:'vault'|'quick'|'assistant';onVault:(id:string)=>void;onSaved:()=>Promise<unknown>}){
 const [unlock,setUnlock]=useState<Unlock|null>(null),[prompt,setPrompt]=useState<'read'|'write'|null>(null),[currentPassword,setCurrentPassword]=useState(''),[password,setPassword]=useState(''),[codes,setCodes]=useState(''),[editing,setEditing]=useState(false),[field,setField]=useState<'password'|'recoveryCodes'>('password'),[value,setValue]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const pending=useRef<'reveal'|'copy'>('reveal'),generation=useRef(0);
 const clear=useCallback(()=>{generation.current++;setUnlock(null);setValue(null);setCurrentPassword('');setPassword('');setCodes('');setEditing(false);setPrompt(null)},[]);
 useEffect(()=>{const hide=()=>clear();window.addEventListener('blur',hide);document.addEventListener('visibilitychange',hide);return()=>{generation.current++;window.removeEventListener('blur',hide);document.removeEventListener('visibilitychange',hide)}},[clear]);
 useEffect(()=>{if(!unlock)return;const timer=setTimeout(clear,Math.max(0,unlock.expiresAt-Date.now()));return()=>clearTimeout(timer)},[unlock,clear]);
 async function read(intent:'reveal'|'copy',key=unlock){if(!key||key.purpose!=='read'||key.expiresAt<=Date.now()){pending.current=intent;setPrompt('read');return}const g=generation.current;setBusy(true);setError('');try{const d=await call<{value:string;expiresAt:number}>('vault',{action:'read',id:a.id,token:key.token,scope,field,intent});if(g!==generation.current)return;if(intent==='copy'){if(!navigator.clipboard){setError('Não foi possível copiar. Use Revelar para consultar.');return}try{await navigator.clipboard.writeText(d.value);toast.success('Credencial copiada.')}catch{setError('A cópia não foi permitida pelo navegador. Use Revelar.')}}else setValue(d.value||'Nenhum conteúdo cadastrado neste campo.')}catch(e){if(g===generation.current){setValue(null);setError((e as Error).message);setUnlock(null)}}finally{setBusy(false)}}
 async function unlockSubmit(e:FormEvent){e.preventDefault();if(!prompt)return;setBusy(true);setError('');const purpose=prompt,g=generation.current;try{const d=await call<{token:string;expiresAt:number}>('vault',{action:'unlock',id:a.id,password:currentPassword,scope,purpose});setCurrentPassword('');if(g!==generation.current)return;const key={...d,purpose};setUnlock(key);setPrompt(null);if(purpose==='write')setEditing(true);else await read(pending.current,key)}catch(e){if(g===generation.current)setError((e as Error).message)}finally{setBusy(false)}}
 async function save(e:FormEvent){e.preventDefault();if(!unlock)return;setBusy(true);setError('');try{await call('vault',{action:'write',id:a.id,token:unlock.token,scope,secret:{...(password?{password}:{}),...(codes?{recoveryCodes:codes}:{})}});clear();toast.success('Credencial salva no Cofre.');await onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="access-module access-credential"><div className="access-detail-heading"><span><LockKeyhole size={16}/>Cofre {a.sensitive?'· credencial sensível':''}</span><h2>{a.label}</h2><p>{a.login}</p></div>{!a.canReveal&&!a.canEdit?<p className="access-notice">Seu usuário pode consultar a conta, mas não acessar esta credencial. A autorização é gerenciada pelo administrador.</p>:scope==='quick'&&!a.quickAccess?<><p className="access-notice">Esta credencial só pode ser aberta dentro do Cofre.</p><Button onClick={()=>onVault(a.id)}>Abrir no Cofre<ArrowUpRight/></Button></>:<><ErrorBox message={error}/>{scope==='assistant'&&!a.quickAccess&&<p className="access-notice">A consulta desta credencial é restrita à seção Cofre. Aqui você pode substituir os campos autorizados após desbloquear.</p>}{a.hasSecret&&a.canReveal&&!editing&&(scope!=='assistant'||a.quickAccess)&&<><Field label="Conteúdo da credencial"><select value={field} onChange={e=>{clear();setField(e.target.value as typeof field)}}><option value="password">Senha</option><option value="recoveryCodes">Códigos de recuperação</option></select></Field><div className="access-secret" aria-label="Credencial">{value===null?'••••••••••••••':value}</div><div className="access-actions"><Button variant="outline" disabled={busy} onClick={()=>value===null?void read('reveal'):setValue(null)}>{value===null?<Eye/>:<EyeOff/>}{value===null?'Revelar':'Ocultar'}</Button><Button variant="outline" disabled={busy} onClick={()=>void read('copy')}><Copy/>Copiar</Button></div></>}{!a.hasSecret&&<p className="access-notice">Nenhuma credencial armazenada nesta conta.</p>}
 {prompt&&<form className="access-form access-unlock" onSubmit={unlockSubmit}><Field label="Sua senha de acesso ao Atlas"><input type="password" required maxLength={128} autoComplete="current-password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></Field><p className="access-caption">Desbloqueio por até um minuto nesta conta. O conteúdo volta a ficar oculto ao sair da janela.</p><div className="access-actions"><Button disabled={busy} type="submit">{busy?'Conferindo…':'Desbloquear'}</Button><Button variant="ghost" type="button" onClick={clear}>Cancelar</Button></div></form>}
 {a.canEdit&&!editing&&!prompt&&<div className="access-actions">{scope!=='quick'?<Button disabled={busy} variant="outline" onClick={()=>{setValue(null);setPrompt('write')}}>{a.hasSecret?'Alterar credencial':'Cadastrar credencial'}</Button>:<Button variant="ghost" onClick={()=>onVault(a.id)}>Editar no Cofre<ArrowUpRight/></Button>}</div>}
 {editing&&<form className="access-form" onSubmit={save}><Field label="Senha da conta"><input type="password" autoComplete="new-password" maxLength={4096} value={password} onChange={e=>setPassword(e.target.value)}/></Field><Field label="Códigos de recuperação"><textarea autoComplete="off" maxLength={20000} value={codes} onChange={e=>setCodes(e.target.value)}/></Field><p className="access-caption">Preencha somente o que deseja substituir. Campos vazios preservam o conteúdo existente.</p><div className="access-actions"><Button disabled={busy||!password&&!codes} type="submit">Salvar credencial</Button><Button type="button" variant="ghost" onClick={clear}>Cancelar</Button></div></form>}
 {unlock&&<button className="access-text-button" onClick={clear}><LockKeyhole size={15}/>Bloquear agora</button>}<p className="access-caption">Revelações, solicitações de cópia e alterações ficam no histórico. O conteúdo da senha não aparece no log.</p></>}</section>;
}
export function AccessLinked({lineId,deviceId,config,lines,onVault}:{lineId?:string;deviceId?:string;config:Config;lines:Line[];onVault:(id:string)=>void}){
 const [open,setOpen]=useState(false),[selected,setSelected]=useState(''),[secret,setSecret]=useState(false);const {data,error,loading,refresh}=useDirectory();
 const linked=data.accounts.filter(a=>!a.archived&&a.methods.some(m=>m.destinations.some(t=>lineId?t.lineId===lineId:t.deviceId===deviceId||Boolean(t.lineId&&lines.some(l=>l.id===t.lineId&&l.deviceId===deviceId)))));
 const active=data.accounts.find(a=>a.id===selected);
 return <div className="access-linked"><Button type="button" variant="outline" onClick={()=>{setOpen(true);setSelected('');setSecret(false);void refresh()}}><KeyRound/>Contas vinculadas{!loading&&!error?' · '+linked.length:''}</Button><Sheet open={open} onOpenChange={setOpen}><SheetContent className="line-sheet"><SheetHeader><SheetTitle>Contas vinculadas</SheetTitle><SheetDescription>Confirmações associadas a esta linha ou aparelho.</SheetDescription></SheetHeader><div className="access-module"><ErrorBox message={error}/>{loading?<p>Carregando…</p>:active?<><Button variant="ghost" onClick={()=>{setSelected('');setSecret(false)}}><ArrowLeft/>Voltar às contas</Button>{secret?<CredentialPanel key={active.id+'-'+active.version} account={active} scope="quick" onVault={id=>{setOpen(false);onVault(id)}} onSaved={refresh}/>:<AccountView account={active} config={config} lines={lines} data={data} onSelect={setSelected} onSecret={()=>setSecret(true)} refresh={refresh}/>}</>:<div className="access-list">{linked.length?linked.map(a=><button className="access-account" key={a.id} onClick={()=>setSelected(a.id)}><strong>{a.label}</strong><small>{a.login}</small><Status account={a} data={data} lines={lines} config={config}/></button>):<p className="access-notice">Nenhuma conta vinculada disponível para seu usuário.</p>}</div>}</div></SheetContent></Sheet></div>;
}
