'use client';
import {useEffect,useMemo,useState,type FormEvent,type ReactNode,type CSSProperties} from 'react';
import {Smartphone,CardSim,MapPin,Plus,Search,Settings2,LayoutDashboard,Wallet,Archive,ChevronRight,ChevronDown,Cloud,MessageCircle,Check,ArrowLeft,History,LoaderCircle,Pencil,ShieldCheck,AlertCircle,LockKeyhole,FlaskConical,ListFilter,ArrowUpRight,ArrowRight,UserRound,Signal} from 'lucide-react';
import {clientId} from '@/lib/client-id';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarGroup,SidebarGroupLabel,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarMenuSub,SidebarMenuSubItem,SidebarTrigger,SidebarInset,useSidebar} from '@/components/ui/sidebar';
import {Collapsible,CollapsibleTrigger,CollapsibleContent} from '@/components/ui/collapsible';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {prepareLine,prepareConfig,checkLineConflicts,deviceSlots,locationOf,parseCost,sameLine} from '@/lib/registration';
import {Button} from '@/components/ui/button';
import HistoryPanel from './history-panel';
import TeamPanel from './team-panel';
import PasswordPanel from './password-panel';
import BackupPanel from './backup-panel';
import {lineDetail,historyEvent,deviceValues,diffValues,type HistoryEvent} from '@/lib/audit';
import type {Actor} from '@/lib/access';
import {Toaster,toast} from 'sonner';
import {defaultConfig,demoConfig,demoLines,newLine,displayNumber,currency,usageLabels,statusLabels,modelOptions,slotOptions,normalizeNumber,formatDataPackage,type Line,type Device,type Config} from '@/lib/atlas';

async function api(path:string,payload?:unknown){const res=await fetch('/api/'+path,payload?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}:{cache:'no-store'});const d=await res.json() as {error?:string;lines:Line[];config:Config;line:Line;user:Actor;history:HistoryEvent[]};if(!res.ok)throw new Error(d.error||'Não foi possível concluir.');return d}
function Field({label,children,wide=false}:{label:string,children:ReactNode,wide?:boolean}){return <div className={'field '+(wide?'wide':'')}><span className="field-label">{label}</span>{children}</div>}
function Choice({value,options,onChange,label}:{value:string,options:[string,string][],onChange:(v:string)=>void,label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue placeholder="Selecione"/></SelectTrigger><SelectContent position="popper">{options.map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select>}
function DeviceVisual({device,large=false}:{device?:Device,large?:boolean}){return <span aria-hidden="true" className={'device-art '+(device?.type||'sim')+(large?' large':'')}>{device?<Smartphone strokeWidth={1.35}/>:<CardSim strokeWidth={1.35}/>}<span>{device?.type==='iphone'?'iOS':device?'Android':'SIM'}</span></span>}
function Metric({icon,title,value,sub,warm,onClick}:{icon:ReactNode,title:string,value:string,sub:string,warm?:boolean,onClick?:()=>void}){const Tag=onClick?'button':'section';return <Tag className={'metric '+(warm?'warm':'')} onClick={onClick}><div className="metric-top"><span className="metric-icon">{icon}</span>{warm&&<span className="metric-badge">Conferir</span>}</div><strong>{value}</strong><span className="metric-caption">{title}</span><small>{sub}</small></Tag>}
function NavButton({active,onClick,children}:{active:boolean,onClick:()=>void,children:ReactNode}){const {isMobile,setOpenMobile}=useSidebar();return <SidebarMenuButton isActive={active} aria-current={active?'page':undefined} className="nav-button" onClick={()=>{onClick();if(isMobile)setOpenMobile(false)}}>{children}</SidebarMenuButton>}
function AtlasNavigation({tab,onNavigate,lineCount,reserveCount}:{tab:string,onNavigate:(id:string)=>void,lineCount:number,reserveCount:number}){
 const [open,setOpen]=useState(false);
 const inSettings=tab==='lines'||tab==='reserve'||tab==='settings';
 useEffect(()=>{if(inSettings)setOpen(true)},[tab,inSettings]);
 const items=[{id:'lines',label:'Minhas linhas',icon:CardSim,count:lineCount},{id:'reserve',label:'Chips em reserva',icon:Archive,count:reserveCount},{id:'settings',label:'Cadastro de aparelhos',icon:Smartphone}];
 return <nav aria-label="Menu principal"><SidebarMenu>
  <SidebarMenuItem><NavButton active={tab==='dashboard'} onClick={()=>onNavigate('dashboard')}><LayoutDashboard/><span>Visão geral</span></NavButton></SidebarMenuItem>
  <Collapsible asChild open={open} onOpenChange={setOpen}>
   <SidebarMenuItem>
    <CollapsibleTrigger asChild><SidebarMenuButton isActive={inSettings} className="nav-button nav-settings-toggle"><Settings2/><span>Configurações</span><ChevronDown className="nav-settings-chevron"/></SidebarMenuButton></CollapsibleTrigger>
    <CollapsibleContent className="nav-settings-content">
     <SidebarMenuSub className="nav-settings-submenu">{items.map(item=><SidebarMenuSubItem key={item.id}><NavButton active={tab===item.id} onClick={()=>onNavigate(item.id)}><item.icon/><span className="nav-submenu-label">{item.label}</span>{item.count!==undefined&&<span className="nav-count">{item.count}</span>}</NavButton></SidebarMenuSubItem>)}</SidebarMenuSub>
    </CollapsibleContent>
   </SidebarMenuItem>
  </Collapsible>
 </SidebarMenu></nav>
}
function slotLabel(slot:string|null){return slot==='eSIM'?'eSIM 1':slot||''}
function lineLocation(l:Line,c:Config){return l.deviceId?c.devices.find(d=>d.id===l.deviceId)?.location||'':l.location}

function OverviewLineCard({line,config,onOpen,onHistory}:{line:Line,config:Config,onOpen:()=>void,onHistory:()=>void}){
 const device=config.devices.find(d=>d.id===line.deviceId),location=lineLocation(line,config);
 const UsageIcon=line.usage==='api'?Cloud:line.usage==='groups'?MessageCircle:Smartphone;
 return <article className="line-card-wrap"><button type="button" className={'overview-line-card '+(line.status==='reserve'?'reserve-card':'')} onClick={onOpen} aria-label={`Ver detalhes de ${line.name}, ${displayNumber(line.number)}`}>
  <span className="line-card-header"><DeviceVisual device={device}/><span className="line-card-identity"><strong title={displayNumber(line.number)}>{displayNumber(line.number)}</strong><span className="line-card-number" title={line.name}>{line.name}</span></span><span aria-hidden="true"/></span>
  <span className="line-card-status"><span className={'status-label '+line.status}><span className="line-status-dot"/>{statusLabels[line.status]}</span><span className="line-card-carrier"><CardSim size={14}/>{line.carrier}</span></span>
  <span className="line-card-metrics"><span><span className="card-field-label"><UserRound size={15}/>Responsável</span><strong className={!line.owner?'attention':''} title={line.owner||'Responsável pendente'}>{line.owner||'A confirmar'}</strong><small>{line.team||'Setor não informado'}</small></span><span><span className="card-field-label"><Wallet size={15}/>Mensalidade</span><strong className={line.cost===null?'unknown-cost':''}>{currency(line.cost)}</strong><small>{line.dueDay?`Vence dia ${line.dueDay}`:line.cost===null?'Adicionar no cadastro':'por mês'}</small></span></span>
  <span className="line-card-data-package"><span className="card-field-label"><Signal size={15}/>Pacote de dados</span><strong title={formatDataPackage(line.dataPackage)||'Não informado'}>{formatDataPackage(line.dataPackage)||'Não informado'}</strong></span>
  <span className={'line-card-location '+(!location?'location-pending':'')}><span className="card-field-label"><MapPin size={15}/>{line.status==='cancelled'?'Último local':line.status==='reserve'&&!device?'Onde está guardado':'Localização do chip'}</span><strong>{device&&location?`${device.model}${line.slot?' · '+slotLabel(line.slot):''}`:location||'Local a confirmar'}</strong><span className="line-card-device">{device&&location?location:device?`${device.model}${line.slot?' · '+slotLabel(line.slot):''}`:line.status==='cancelled'?'Sem vínculo atual':'Chip guardado · sem aparelho'}</span>{line.notes&&<span className="line-card-note" title={line.notes}>{line.notes}</span>}</span>
  <span className="line-card-footer"><span className="line-card-usage"><UsageIcon size={15}/><span>{line.platform||usageLabels[line.usage]}</span></span><span className="line-card-action">Ver linha<ArrowRight size={17}/></span></span>
 </button><button type="button" className="history-shortcut" aria-label={`Histórico de ${line.name}`} title="Histórico da linha" onClick={onHistory}><History size={17}/></button></article>
}

export default function AtlasApp({localMode=false,onLogout}:{localMode?:boolean;onLogout?:()=>void}={}){
 const [lines,setLines]=useState<Line[]>([]),[config,setConfig]=useState<Config>(defaultConfig),[examples,setExamples]=useState<Line[]>(demoLines),[exampleConfig,setExampleConfig]=useState<Config>(demoConfig),[demo,setDemo]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tab,setTab]=useState('dashboard'),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[statusFilter,setStatusFilter]=useState('all'),[carrierFilter,setCarrierFilter]=useState('all'),[editing,setEditing]=useState<Line|null>(null),[saving,setSaving]=useState(false),[deviceEditing,setDeviceEditing]=useState<Device|null>(null),[deviceBusy,setDeviceBusy]=useState(false),[user,setUser]=useState<Actor|null>(null),[accessError,setAccessError]=useState(''),[historyLine,setHistoryLine]=useState<Line|null>(null),[exampleHistory,setExampleHistory]=useState<Record<string,HistoryEvent[]>>(()=>Object.fromEntries(demoLines.map(l=>[l.id!,[historyEvent({id:'demo-created-'+l.id,created_at:new Date().toISOString(),data:JSON.stringify(l),version:1,previous:null,detail:JSON.stringify(lineDetail(null,l,demoConfig,{id:'demo',name:'Demonstração',email:'Dados fictícios'}))})]])));
 const current=demo?examples:lines,cfg=demo?exampleConfig:config;
 async function load(){setLoading(true);setError('');setAccessError('');try{let identity;try{identity=await api('me');setUser(identity.user)}catch(e){setUser(null);setAccessError((e as Error).message);return}const [a,b]=await Promise.all([api('lines'),api('settings')]);setLines(a.lines);setConfig(b.config);if(!localMode&&!a.lines.length)setDemo(true)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const visible=useMemo(()=>{const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const q=normalize(query.trim()),digits=normalizeNumber(query.trim());return current.filter(l=>{if(tab==='reserve'&&l.status!=='reserve')return false;if(statusFilter!=='all'&&l.status!==statusFilter)return false;if(carrierFilter!=='all'&&l.carrier!==carrierFilter)return false;if(filter==='reserve'&&l.status!=='reserve')return false;if(filter==='pending'&&(l.status==='cancelled'||(lineLocation(l,cfg)&&l.owner.trim())))return false;if(['api','groups','phone','other'].includes(filter)&&l.usage!==filter)return false;const device=cfg.devices.find(d=>d.id===l.deviceId);return normalize([l.number,l.name,l.owner,l.team,l.location,l.notes,l.carrier,l.platform,usageLabels[l.usage],device?.model,device?.location,device?.name].join(' ')).includes(q)||(/^\d{3,}$/.test(digits)&&l.number.includes(digits))})},[current,cfg,filter,query,statusFilter,carrierFilter,tab]);
 const cost=current.filter(l=>l.status!=='cancelled').reduce((s,l)=>s+(l.cost??0),0),missing=current.filter(l=>l.status!=='cancelled'&&l.cost===null).length,pending=current.filter(l=>l.status!=='cancelled'&&(!lineLocation(l,cfg)||!l.owner.trim())).length,reserves=current.filter(l=>l.status==='reserve').length;
 function clearFilters(){setQuery('');setFilter('all');setStatusFilter('all');setCarrierFilter('all')}
 const filtered=Boolean(query||filter!=='all'||statusFilter!=='all'||carrierFilter!=='all');

 async function saveLine(input:Line){setSaving(true);try{const l=prepareLine(input,cfg);checkLineConflicts(l,current);if(demo){const previous=examples.find(x=>x.id===l.id);if(previous&&sameLine(previous,l)){setEditing(null);return}const result={...l,id:l.id||'demo-'+clientId(),version:l.version+1,updatedAt:new Date().toISOString()};setExamples(old=>old.some(x=>x.id===result.id)?old.map(x=>x.id===result.id?result:x):[result,...old]);setExampleHistory(old=>({...old,[result.id]:[historyEvent({id:clientId(),created_at:result.updatedAt,data:JSON.stringify(result),version:result.version,previous:null,detail:JSON.stringify(lineDetail(previous||null,result,cfg,{id:'demo',name:'Demonstração',email:'Dados fictícios'}))}),...(old[result.id]||[])]}));toast.success('Exemplo atualizado.')}else{const d=await api('lines',l);setLines(old=>old.some(x=>x.id===d.line.id)?old.map(x=>x.id===d.line.id?d.line:x):[d.line,...old]);toast.success('Linha salva.')}setEditing(null)}catch(e){toast.error((e as Error).message)}finally{setSaving(false)}}
 async function saveConfig(input:Config){const c=prepareConfig(input,current);if(demo){const events:Record<string,HistoryEvent>={};for(const l of examples){const before=exampleConfig.devices.find(d=>d.id===l.deviceId),after=c.devices.find(d=>d.id===l.deviceId);if(before&&after){const changes=diffValues(deviceValues(before),deviceValues(after));if(changes.length)events[l.id!]={id:clientId(),date:new Date().toISOString(),kind:'device',actor:{id:'demo',name:'Demonstração',email:'Dados fictícios'},changes,legacy:false,incomplete:false}}}setExampleHistory(old=>{const next={...old};for(const [id,event] of Object.entries(events))next[id]=[event,...(old[id]||[])];return next});setExampleConfig({...c,version:c.version+1});toast.success('Configuração do exemplo atualizada.');return c}const d=await api('settings',c);setConfig(d.config);toast.success('Configurações salvas.');return d.config as Config}
 async function saveDevice(d:Device){setDeviceBusy(true);try{const next={...cfg,devices:cfg.devices.some(x=>x.id===d.id)?cfg.devices.map(x=>x.id===d.id?d:x):[...cfg.devices,d]};await saveConfig(next);if(editing&&editing.status!=='cancelled')setEditing({...editing,deviceId:d.id,slot:deviceSlots(d).find(slot=>!current.some(l=>l.id!==editing.id&&l.deviceId===d.id&&l.slot===slot))||null});setDeviceEditing(null)}catch(e){toast.error((e as Error).message)}finally{setDeviceBusy(false)}}
 function freshDevice(){setDeviceEditing({id:clientId(),name:'',type:'android',model:modelOptions.android[0],location:'',owner:'',slots:['Slot 1']})}
 useEffect(()=>{if(localMode)return;const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!context)return;const controller=new AbortController();const tool={name:'atlas_list_lines',description:'Lista as linhas visíveis no modo atual, incluindo aparelho e local.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Use um objeto vazio.');return {mode:demo?'demonstration':'saved',lines:current.map(l=>({id:l.id,number:displayNumber(l.number),name:l.name,location:lineLocation(l,cfg),owner:l.owner,status:l.status}))}}};try{void Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{})}catch{}return()=>controller.abort()},[current,cfg,demo,localMode]);
 if(!user)return <main className="access-screen"><img src="/favicon.svg" width="56" height="56" alt="Atlas"/><h1>Atlas Linhas</h1>{loading?<p>Conferindo seu acesso...</p>:<><p role="alert">{accessError||'Entre com sua conta para continuar.'}</p>{localMode?<Button className="action-primary" onClick={()=>window.location.reload()}>Voltar ao acesso</Button>:<a className="action-primary" href="/signin-with-chatgpt?return_to=%2F" target="_top">Entrar com ChatGPT</a>}<Button variant="outline" onClick={()=>void load()}>Verificar acesso novamente</Button></>}</main>;
 function navigate(id:string){setTab(id);clearFilters()}
 function showFilter(value:string){setTab('dashboard');clearFilters();setFilter(value)}
 const title=tab==='settings'?'Configurações':tab==='reserve'?'Chips em reserva':tab==='lines'?'Minhas linhas':'Visão geral';
 return <div className="atlas-app"><Toaster richColors position="top-right"/><SidebarProvider style={{'--sidebar-width':'274px'} as CSSProperties}>
 <Sidebar variant="floating" className="atlas-sidebar"><SidebarHeader className="brand-header"><span className="brand-mark"><img src="/favicon.svg" alt="" width="50" height="50"/></span><div className="wordmark">Atlas<small>Gestão de linhas telefônicas</small></div></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>OPERAÇÃO</SidebarGroupLabel><AtlasNavigation tab={tab} onNavigate={navigate} lineCount={current.length} reserveCount={reserves}/></SidebarGroup></SidebarContent><SidebarFooter>{pending>0&&<div className="agent-card"><div><MapPin size={16}/><strong>Pendências de cadastro</strong></div><p>{pending} {pending===1?'linha precisa':'linhas precisam'} de revisão</p><small>Confira a localização e o responsável.</small><button className="sidebar-link" onClick={()=>showFilter('pending')}>Conferir pendências<ChevronRight size={14}/></button></div>}<div className="profile"><span>ON</span><div><strong>{user.name}</strong><small>{user.role==='admin'?'Administrador':'Operador'}</small></div><ShieldCheck size={16}/></div></SidebarFooter></Sidebar>
 <SidebarInset className="app-inset"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="sidebar-toggle"/><span>Atlas Linhas</span><ChevronRight size={13}/><strong>{title}</strong></div><div className="topbar-right"><span className={'badge '+(demo?'amber':'mint')}>{demo?<FlaskConical size={14}/>:<ShieldCheck size={14}/>} {demo?'Demonstração':loading?'Carregando':error?'Conexão indisponível':'Meus cadastros'}</span>{localMode?<button className="session-link" onClick={onLogout}>Sair</button>:<a className="session-link" href="/signout-with-chatgpt?return_to=%2F" target="_top">Sair</a>}</div></header>
 <main className={'workspace '+(tab==='dashboard'?'dashboard-workspace':'')}>
 <div className="page-heading"><div><p className="eyebrow"><CardSim size={14}/>CONTROLE DE TELEFONIA</p><h1>{tab==='dashboard'?<>Controle de <span>linhas.</span></>:title}</h1><p className="heading-sub">{tab==='settings'?'Cadastre aparelhos, operadoras e locais da empresa.':tab==='reserve'?'Saiba onde cada chip está guardado e encontre a reserva certa.':'Números, aparelhos e responsáveis da sua operação.'}</p></div>{tab!=='settings'&&<Button className="action-primary" disabled={loading||Boolean(error)&&!demo} onClick={()=>setEditing({...newLine(),status:tab==='reserve'?'reserve':'active',carrier:cfg.carriers[0]||'Vivo'})}><Plus size={17}/>Nova linha</Button>}</div>
 {demo&&<div className="demo-banner"><FlaskConical size={16}/><span><strong>Demonstração</strong><span className="demo-description"> · Explore com dados de exemplo.</span></span><button onClick={()=>{setDemo(false);navigate('dashboard')}}>Usar com meus dados<ChevronRight size={15}/></button></div>}
 {error&&<div className="error-banner" role="alert"><AlertCircle/>{error}<Button variant="outline" onClick={()=>void load()}>Tentar novamente</Button></div>}
 {tab!=='settings'&&<>
 {tab==='dashboard'&&<div className="metrics"><Metric icon={<CardSim/>} title="Linhas cadastradas" value={String(current.length).padStart(2,'0')} sub={`${current.filter(l=>l.status==='active').length} em uso na empresa`} onClick={()=>showFilter('all')}/><Metric icon={<Wallet/>} title="Custo mensal" value={currency(cost)} sub={missing?`${missing} sem custo · total parcial`:'Total das linhas não canceladas'}/><Metric icon={<Archive/>} title="Chips em reserva" value={String(reserves).padStart(2,'0')} sub="Disponíveis para a operação" onClick={()=>showFilter('reserve')}/><Metric icon={<MapPin/>} title="Cadastros pendentes" value={String(pending).padStart(2,'0')} sub="Sem local ou responsável" warm onClick={()=>showFilter('pending')}/></div>}
 <section className={tab==='dashboard'?'overview-inventory':'lines-panel'}><div className="panel-heading"><div><h2>{tab==='reserve'?'Linhas em reserva':tab==='dashboard'?'Suas linhas':'Inventário de linhas'} <span>{visible.length}</span></h2><p>{tab==='reserve'?'Local, identificação e observação de cada reserva.':'Acompanhe a utilização e a localização dos seus números.'}</p></div><label className="search-box"><Search size={18}/><input aria-label="Buscar linhas" placeholder="Número, aparelho, pessoa ou local..." value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 <div className="inventory-filters"><div><span className="sr-only">Filtrar por situação</span><Choice label="Filtrar por situação" value={statusFilter} options={tab==='reserve'?[['all','Em reserva']]:[['all','Todas as situações'],...Object.entries(statusLabels)]} onChange={setStatusFilter}/></div><div><Choice label="Filtrar por operadora" value={carrierFilter} options={[["all","Todas as operadoras"],...Array.from(new Set([...cfg.carriers,...current.map(l=>l.carrier)])).map(v=>[v,v] as [string,string])]} onChange={setCarrierFilter}/></div>{filtered&&<Button variant="ghost" onClick={clearFilters}>Limpar filtros</Button>}<span role="status" aria-live="polite">{visible.length} {visible.length===1?'linha encontrada':'linhas encontradas'}</span></div>
 <div className="filter-row">{[['all','Todas'],['api','API oficial'],['groups','Grupos'],['phone','Celulares'],['other','Outros usos'],['reserve','Reservas'],['pending','Pendências']].map(([v,t])=><button key={v} aria-pressed={filter===v} className={filter===v?'selected':''} onClick={()=>setFilter(v)}>{t}</button>)}<span className="filter-help"><ListFilter size={14}/>{visible.length} {visible.length===1?'linha':'linhas'}</span></div>
 {loading?<div className="empty-state"><LoaderCircle className="spin"/><h3>Carregando suas linhas...</h3></div>:<>{tab==='dashboard'?<div className="line-card-grid">{visible.map(line=><OverviewLineCard key={line.id} line={line} config={cfg} onOpen={()=>setEditing({...line})} onHistory={()=>setHistoryLine(line)}/>)}</div>:<><div className="row-head"><span></span><span>Número / operadora</span><span>Finalidade</span><span>Local / aparelho</span><span>Responsável</span><span>Mensalidade</span><span></span></div><div className="line-rows">{visible.map(l=>{const device=cfg.devices.find(d=>d.id===l.deviceId),loc=lineLocation(l,cfg);return <div className="line-row-wrap" key={l.id}><button className={'line-row '+(l.status==='reserve'?'is-reserve':'')} onClick={()=>setEditing({...l})} aria-label={`Editar ${l.name}, ${displayNumber(l.number)}`}><DeviceVisual device={device}/><span className="number-cell"><strong>{displayNumber(l.number)}</strong><small><span className={'carrier-label carrier-'+l.carrier.toLowerCase()}>{l.carrier}</span><span className={'status-label '+l.status}>{statusLabels[l.status]}</span></small></span><span><strong>{l.name}</strong><small className="usage">{l.usage==='api'?<Cloud size={13}/>:l.usage==='groups'?<MessageCircle size={13}/>:null}{l.platform||usageLabels[l.usage]}</small></span><span className="location-cell"><strong className={!loc?'attention':''}>{loc||'Local a confirmar'}</strong><small>{device?<>{device.model} · {slotLabel(l.slot)}</>:l.notes||'Chip guardado · sem aparelho'}</small></span><span className="owner-cell"><span className="avatar">{l.owner.slice(0,1)||'?'}</span><span><strong>{l.owner||'Não informado'}</strong><small>{l.team||device?.owner||'Responsável pela linha'}</small></span></span><span className="money-cell"><strong>{currency(l.cost)}</strong><small>{l.dueDay?`Vence dia ${l.dueDay}`:'por mês'}</small></span><ChevronRight className="row-arrow" size={17}/></button><button type="button" className="history-shortcut" aria-label={`Histórico de ${l.name}`} title="Histórico da linha" onClick={()=>setHistoryLine(l)}><History size={17}/></button></div>})}</div></>}{!visible.length&&<div className="empty-state"><CardSim size={42}/><h3>{current.length?'Nenhuma linha encontrada':'Tudo pronto para organizar suas linhas'}</h3><p>{current.length?'Ajuste a busca ou os filtros.':localMode?'Cadastre seu primeiro número.':'Cadastre seu primeiro número ou explore o exemplo.'}</p>{current.length>0&&filtered&&<Button variant="outline" onClick={clearFilters}>Limpar busca e filtros</Button>}{!current.length&&<div><Button onClick={()=>setEditing({...newLine(),carrier:cfg.carriers[0]||'Vivo'})}><Plus/>Cadastrar linha</Button>{!localMode&&<Button variant="outline" onClick={()=>setDemo(true)}>Ver demonstração</Button>}</div>}</div>}</>}
 <footer className="panel-footer"><span>{visible.length} de {current.length} linhas</span><span><ShieldCheck size={14}/>{demo?'Modo demonstração':'Cadastros salvos'}</span></footer></section>
 </>}
 {tab==='settings'&&<ConfigPanel config={cfg} onSave={saveConfig} onNewDevice={freshDevice} onEditDevice={setDeviceEditing} lines={current}/>}
 {tab==='settings'&&localMode&&!demo&&<PasswordPanel/>}
 {tab==='settings'&&user.role==='admin'&&!demo&&<TeamPanel localMode={localMode}/>}
 {tab==='settings'&&<BackupPanel admin={user.role==='admin'} demo={demo} lines={current} config={cfg} onRestored={async()=>{const [a,b]=await Promise.all([api('lines'),api('settings')]);setLines(a.lines);setConfig(b.config);setEditing(null);setHistoryLine(null)}}/>}
 {!localMode&&!demo&&current.length>0&&<button className="example-link" onClick={()=>{setDemo(true);navigate('dashboard')}}>Explorar demonstração</button>}
 <footer className="page-footer"><span>Atlas Linhas <span className="footer-separator">/</span> {cfg.company}</span><span><LockKeyhole size={13}/>{demo?'Dados de exemplo':'Controle de telefonia'}</span></footer></main></SidebarInset></SidebarProvider>
 <Sheet open={Boolean(editing)} onOpenChange={o=>{if(!o&&!saving)setEditing(null)}}><SheetContent className="line-sheet" showCloseButton={!saving}><SheetHeader><SheetTitle>{editing?.id?'Detalhes da linha':'Nova linha'}</SheetTitle><SheetDescription>{editing?.id?displayNumber(editing.number):'Cadastre o número e indique onde ele fica.'}</SheetDescription></SheetHeader>{editing&&<LineEditor key={editing.id||'new'} line={editing} config={cfg} lines={current} demo={demo} demoEvents={exampleHistory[editing.id||'']||[]} busy={saving} onChange={setEditing} onSave={saveLine} onNewDevice={freshDevice}/>}</SheetContent></Sheet>
 <Sheet open={Boolean(historyLine)} onOpenChange={open=>{if(!open)setHistoryLine(null)}}><SheetContent className="line-sheet"><SheetHeader><SheetTitle>Trajetória do número</SheetTitle><SheetDescription>{historyLine?.name} · {historyLine&&displayNumber(historyLine.number)}</SheetDescription></SheetHeader>{historyLine?.id&&<HistoryPanel key={historyLine.id} lineId={historyLine.id} demo={demo} demoEvents={exampleHistory[historyLine.id]||[]}/>}</SheetContent></Sheet>
 <Dialog open={Boolean(deviceEditing)} onOpenChange={o=>{if(!o&&!deviceBusy)setDeviceEditing(null)}}><DialogContent className="device-dialog"><DialogHeader><DialogTitle>{cfg.devices.some(d=>d.id===deviceEditing?.id)?'Editar aparelho':'Cadastrar aparelho'}</DialogTitle><DialogDescription>Escolha o tipo e dê um nome fácil de reconhecer.</DialogDescription></DialogHeader>{deviceEditing&&<DeviceEditor key={deviceEditing.id} device={deviceEditing} busy={deviceBusy} onSave={saveDevice}/>}</DialogContent></Dialog>
 </div>
}

function LineEditor({line:l,config:c,lines,demo,demoEvents,busy,onChange,onSave,onNewDevice}:{line:Line,config:Config,lines:Line[],demo:boolean,demoEvents:HistoryEvent[],busy:boolean,onChange:(l:Line)=>void,onSave:(l:Line)=>void,onNewDevice:()=>void}){
 const [cost,setCost]=useState(l.cost===null?'':(l.cost/100).toFixed(2).replace('.',','));
 const originalPackage=formatDataPackage(l.dataPackage),legacyPackage=Boolean(originalPackage&&!/^\d+(?:,\d+)? GB$/.test(originalPackage));
 const [packageAmount,setPackageAmount]=useState(legacyPackage?'':originalPackage.replace(/ GB$/,'')),[replacePackage,setReplacePackage]=useState(false);

 const set=<K extends keyof Line>(k:K,v:Line[K])=>onChange({...l,[k]:v});const device=c.devices.find(d=>d.id===l.deviceId);

 const freeSlots=(d:Device)=>deviceSlots(d).filter(slot=>!lines.some(other=>other.id!==l.id&&other.deviceId===d.id&&other.slot===slot));
 function submit(e:FormEvent){e.preventDefault();try{onSave(prepareLine({...l,cost:parseCost(cost),dataPackage:legacyPackage&&!replacePackage?l.dataPackage:formatDataPackage(packageAmount)},c))}catch(e){toast.error((e as Error).message)}}

 return <Tabs defaultValue="info" className="editor-tabs"><TabsList><TabsTrigger value="info">Cadastro</TabsTrigger><TabsTrigger value="history" disabled={!l.id}><History/> Histórico</TabsTrigger></TabsList><TabsContent value="info"><form onSubmit={submit}><fieldset disabled={busy}><div className="editor-device"><DeviceVisual device={device} large/><div><strong>{device?.name||'Chip sem aparelho'}</strong><p>{device?.model||'Registre o local onde está guardado.'}</p>{device&&<small><MapPin size={13}/>{device.location||'Local a confirmar'}</small>}</div></div><div className="form-grid">
 <Field label="Número com DDD"><Input aria-label="Número com DDD" value={displayNumber(l.number)} inputMode="tel" required onChange={e=>set('number',normalizeNumber(e.target.value))}/></Field>
 <Field label="Operadora"><Choice label="Operadora" value={l.carrier} options={Array.from(new Set([...c.carriers,l.carrier].filter(Boolean))).map(v=>[v,v])} onChange={v=>set('carrier',v)}/></Field>
 <Field label="Identificação da linha" wide><Input aria-label="Identificação da linha" placeholder="Ex.: Atendimento principal" required value={l.name} onChange={e=>set('name',e.target.value)}/></Field>
 <Field label="Situação"><Choice label="Situação" value={l.status} options={Object.entries(statusLabels)} onChange={v=>onChange(v==='cancelled'?{...l,status:'cancelled',location:locationOf(l,c),deviceId:null,slot:null}:{...l,status:v as Line['status']})}/></Field>
 <Field label="Uso do número"><Choice label="Uso do número" value={l.usage} options={Object.entries(usageLabels)} onChange={v=>set('usage',v as Line['usage'])}/></Field>
 <Field label="Sistema / uso virtual" wide><Input aria-label="Sistema ou uso virtual" placeholder="Ex.: Atlas / WhatsApp API" value={l.platform} onChange={e=>set('platform',e.target.value)}/></Field>
 <div className="form-section wide"><Smartphone size={17}/>Onde está o chip?</div>
 {l.status==='cancelled'?<p className="registration-notice wide">Linha cancelada: o cadastro e o histórico são mantidos, e o slot fica livre. Para voltar a usar, altere a situação e escolha o aparelho novamente.</p>:<Field label="Aparelho vinculado" wide><Choice label="Aparelho vinculado" value={l.deviceId||'none'} options={[["none","Sem aparelho / chip guardado"],...c.devices.map(d=>[d.id,`${d.name} · ${d.model}`] as [string,string])]} onChange={v=>onChange({...l,deviceId:v==='none'?null:v,slot:v==='none'?null:freeSlots(c.devices.find(d=>d.id===v)!)[0]||null})}/><button type="button" className="text-action" onClick={onNewDevice}><Plus size={14}/>Cadastrar iPhone ou Android</button></Field>}
 {device?<><Field label="Slot do chip"><Choice label="Slot do chip" value={l.slot||''} options={freeSlots(device).map(v=>[v,slotLabel(v)])} onChange={v=>set('slot',v as Line['slot'])}/><small>{freeSlots(device).length?'Apenas slots livres ou desta linha.':'Todos os slots estão ocupados. Escolha outro aparelho ou mova a linha que ocupa o slot.'}</small></Field><div className="device-location"><span>Local do aparelho</span><strong>{device.location||'Local a confirmar'}</strong><small>Atualize em Configurações → Aparelhos.</small></div></>:<Field label={l.status==='cancelled'?'Último local registrado':'Onde está guardado?'} wide><Input aria-label="Onde está guardado?" list="line-locations" placeholder="Ex.: Armário da TI, gaveta 2" value={l.location} onChange={e=>set('location',e.target.value)}/><datalist id="line-locations">{c.locations.map(v=><option value={v} key={v}/>)}</datalist></Field>}
 {l.status!=='cancelled'&&(!locationOf(l,c)||!l.owner.trim())&&<p className="registration-notice wide">Você pode salvar agora. Ficará pendente: {[!locationOf(l,c)&&'localização',!l.owner.trim()&&'responsável'].filter(Boolean).join(' e ')}.</p>}<Field label="Observação / como encontrar" wide><Textarea aria-label="Observação" placeholder="Ex.: Envelope azul com etiqueta RESERVA 01." value={l.notes} onChange={e=>set('notes',e.target.value)}/></Field>
 <Field label="Responsável"><Input aria-label="Responsável" value={l.owner} placeholder="Pessoa ou setor" onChange={e=>set('owner',e.target.value)}/></Field><Field label="Setor"><Input aria-label="Setor" value={l.team} onChange={e=>set('team',e.target.value)}/></Field>
 <Field label="Mensalidade (R$)"><Input aria-label="Mensalidade" value={cost} inputMode="decimal" placeholder="Não informado" onChange={e=>setCost(e.target.value)}/></Field><Field label="Dia de vencimento"><Input aria-label="Dia de vencimento" type="number" min="1" max="31" value={l.dueDay??''} onChange={e=>set('dueDay',e.target.value?Number(e.target.value):null)}/></Field>
 <Field label="Pacote de dados ativo" wide>{legacyPackage&&!replacePackage?<div><span>{originalPackage}</span><button type="button" className="text-action" onClick={()=>setReplacePackage(true)}>Informar em GB</button></div>:<div className="data-package-input"><Input aria-label="Pacote de dados ativo em GB" inputMode="decimal" pattern="[0-9]+([,.][0-9]+)?" maxLength={97} title="Informe apenas um número, como 25 ou 2,5." placeholder="Ex.: 25" value={packageAmount} onChange={e=>setPackageAmount(e.target.value)}/><span aria-hidden="true">GB</span></div>}</Field>
 </div><div className="editor-footer"><small>{demo?'Alterações somente na demonstração.':'Salvo para consultar de qualquer dispositivo.'}</small><Button type="submit" className="action-primary" disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Check/>}{busy?'Salvando...':demo?'Aplicar no exemplo':'Salvar linha'}</Button></div></fieldset></form></TabsContent><TabsContent value="history">{l.id&&<HistoryPanel lineId={l.id} demo={demo} demoEvents={demoEvents}/>}</TabsContent></Tabs>
}

function DeviceEditor({device,busy,onSave}:{device:Device,busy:boolean,onSave:(d:Device)=>void}){const [d,setD]=useState(device),[custom,setCustom]=useState(!modelOptions[device.type].includes(device.model));return <form onSubmit={e=>{e.preventDefault();if(!d.model.trim()){toast.error('Informe o modelo.');return}onSave(d)}}><fieldset disabled={busy}><div className="device-selection"><DeviceVisual device={d} large/><div><RadioGroup value={d.type} onValueChange={v=>{const type=v as Device['type'];setD({...d,type,model:modelOptions[type][0]});setCustom(false)}} className="os-options"><label><RadioGroupItem value="iphone"/>iPhone</label><label><RadioGroupItem value="android"/>Android</label></RadioGroup><p>Selecione o sistema e o modelo do aparelho.</p></div></div><div className="form-grid"><Field label="Modelo" wide><Choice label="Modelo" value={custom?'other':d.model} options={[...modelOptions[d.type].map(v=>[v,v] as [string,string]),['other','Outro modelo...']]} onChange={v=>{setCustom(v==='other');setD({...d,model:v==='other'?'':v})}}/>{custom&&<Input aria-label="Outro modelo" required placeholder="Digite o modelo" value={d.model} onChange={e=>setD({...d,model:e.target.value})}/>}</Field><Field label="Nome do aparelho" wide><Input aria-label="Nome do aparelho" required placeholder="Ex.: Operacional 01" value={d.name} onChange={e=>setD({...d,name:e.target.value})}/></Field><Field label="Slots disponíveis no aparelho" wide><div className="slot-choices">{Array.from(new Set([...slotOptions,...deviceSlots(d)])).map(slot=><label key={slot}><Checkbox checked={deviceSlots(d).includes(slot)} onCheckedChange={checked=>setD({...d,slots:checked?[...deviceSlots(d),slot]:deviceSlots(d).filter(s=>s!==slot)})}/>{slotLabel(slot)}</label>)}</div><Button type="button" variant="outline" disabled={Array.from({length:98},(_,i)=>`eSIM ${i+2}`).every(s=>deviceSlots(d).includes(s))} onClick={()=>{const slot=Array.from({length:98},(_,i)=>`eSIM ${i+2}`).find(s=>!deviceSlots(d).includes(s));if(slot)setD({...d,slots:[...deviceSlots(d),slot]})}}><Plus size={16}/>Adicionar eSIM</Button><small>Cada opção recebe uma linha. Os eSIMs representam perfis cadastrados; isso não indica uso simultâneo.</small>{!device.slots&&<small>Confira os slots deste aparelho já cadastrado antes de salvar.</small>}</Field><Field label="Local do aparelho"><Input aria-label="Local do aparelho" placeholder="Ex.: Sala da TI" value={d.location} onChange={e=>setD({...d,location:e.target.value})}/></Field><Field label="Responsável pelo aparelho"><Input aria-label="Responsável pelo aparelho" value={d.owner} onChange={e=>setD({...d,owner:e.target.value})}/></Field></div><div className="editor-footer"><Button type="submit" disabled={busy} className="action-primary">{busy?<LoaderCircle className="spin"/>:<Check/>}Salvar aparelho</Button></div></fieldset></form>}

function ConfigPanel({config:c,onSave,onNewDevice,onEditDevice,lines}:{config:Config,onSave:(c:Config)=>Promise<Config>,onNewDevice:()=>void,onEditDevice:(d:Device)=>void,lines:Line[]}){const [company,setCompany]=useState(c.company),[carriers,setCarriers]=useState(c.carriers.join('\n')),[locations,setLocations]=useState(c.locations.join('\n')),[busy,setBusy]=useState(false);useEffect(()=>{setCompany(c.company);setCarriers(c.carriers.join('\n'));setLocations(c.locations.join('\n'))},[c]);const split=(s:string)=>Array.from(new Set(s.split(/\n|,/).map(x=>x.trim()).filter(Boolean)));return <div className="settings-layout"><section className="lines-panel"><div className="panel-heading"><div><h2>Aparelhos <span>{c.devices.length}</span></h2><p>Um aparelho pode ter mais de uma linha.</p></div><Button variant="outline" onClick={onNewDevice}><Plus/>Novo aparelho</Button></div><div className="device-grid">{c.devices.map(d=><button className="device-card" key={d.id} onClick={()=>onEditDevice({...d})}><DeviceVisual device={d} large/><div><span className="os-tag">{d.type==='iphone'?'iPhone':'Android'}</span><h3>{d.name}</h3><p>{d.model}</p><small><MapPin size={13}/>{d.location||'Local a confirmar'}</small><small>{lines.filter(l=>l.deviceId===d.id).length} linha(s) · {deviceSlots(d).map(slotLabel).join(' / ')}</small></div><Pencil size={16}/></button>)}{!c.devices.length&&<div className="empty-state"><Smartphone size={35}/><h3>Cadastre o primeiro aparelho</h3><p>Escolha iPhone ou Android e indique o modelo.</p></div>}</div></section><section className="lines-panel settings-basics"><h2>Dados e locais</h2><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await onSave({...c,company,carriers:split(carriers),locations:split(locations)})}catch(err){toast.error((err as Error).message)}finally{setBusy(false)}}}><fieldset disabled={busy}><Field label="Empresa"><Input aria-label="Empresa" required value={company} onChange={e=>setCompany(e.target.value)}/></Field><Field label="Operadoras · uma por linha"><Textarea aria-label="Operadoras" required value={carriers} onChange={e=>setCarriers(e.target.value)}/></Field><Field label="Locais frequentes · um por linha"><Textarea aria-label="Locais frequentes" value={locations} onChange={e=>setLocations(e.target.value)}/></Field><Button type="submit" className="action-primary" disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Check/>}Salvar configurações</Button></fieldset></form></section></div>}
