'use client';
import {useEffect,useState} from 'react';
import {History,LoaderCircle,ArrowRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import type {HistoryEvent} from '@/lib/audit';
export default function HistoryPanel({lineId,demo=false,demoEvents=[]}:{lineId:string;demo?:boolean;demoEvents?:HistoryEvent[]}){
 const [events,setEvents]=useState<HistoryEvent[]>([]),[cursor,setCursor]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(next:string|null=null,signal?:AbortSignal){setBusy(true);setError('');try{const response=await fetch('/api/history?id='+encodeURIComponent(lineId)+(next?'&cursor='+encodeURIComponent(next):''),{cache:'no-store',signal});const data=await response.json() as {error?:string;history:HistoryEvent[];nextCursor:string|null};if(!response.ok)throw new Error(data.error||'Não foi possível carregar o histórico.');if(signal?.aborted)return;setEvents(old=>next?[...old,...data.history]:data.history);setCursor(data.nextCursor)}catch(e){if(!signal?.aborted)setError((e as Error).message)}finally{if(!signal?.aborted)setBusy(false)}}
 useEffect(()=>{setEvents([]);setCursor(null);setError('');const controller=new AbortController();if(!demo)void load(null,controller.signal);return()=>controller.abort()},[lineId,demo]);
 const shown=demo?demoEvents:events;
 return <div className="timeline-panel">{demo&&<p className="registration-notice">Histórico de demonstração. As alterações dos exemplos duram apenas nesta sessão.</p>}<div className="audit-timeline">{shown.map(event=><article key={event.id}><span className="audit-dot"><History size={14}/></span><header><strong>{event.kind==='created'?'Linha cadastrada':event.kind==='device'?'Aparelho atualizado':event.kind==='restored'?'Backup restaurado':'Cadastro alterado'}</strong><time dateTime={event.date}>{new Date(event.date).toLocaleString('pt-BR')}</time></header><p className="audit-author">{event.actor?`${event.actor.name} · ${event.actor.email}`:'Autor não registrado'}</p>{event.legacy&&<p className="audit-legacy">Registro anterior ao histórico detalhado. Dados antigos do aparelho não foram registrados.{event.incomplete?' Sem versão anterior disponível; abaixo estão os valores que foram salvos.':''}</p>}<dl>{event.changes.map(change=><div className="audit-change" key={change.field}><dt>{change.field}</dt><dd><span className="audit-before">{change.before}</span><ArrowRight size={14}/><span className="audit-after">{change.after}</span></dd></div>)}</dl>{!event.changes.length&&<p>Nenhuma diferença entre os valores registrados.</p>}</article>)}</div>{busy&&<p className="audit-loading" role="status"><LoaderCircle className="spin" size={16}/>Carregando histórico...</p>}{error&&<div role="alert"><p>{error}</p><Button variant="outline" onClick={()=>void load(cursor)}>Tentar novamente</Button></div>}{!busy&&!error&&!shown.length&&<p>Nenhuma alteração registrada para esta linha.</p>}{!demo&&cursor&&!error&&<Button variant="outline" disabled={busy} onClick={()=>void load(cursor)}>Carregar alterações anteriores</Button>}</div>
}
