'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {toast} from 'sonner';
type Member={email:string;name:string;role:string;active:number;is_owner:number;version:number;joined:number};
export default function TeamPanel({localMode=false}:{localMode?:boolean}){
 const [password,setPassword]=useState(''),[resetEmail,setResetEmail]=useState(''),[resetPassword,setResetPassword]=useState('');
 const [members,setMembers]=useState<Member[]>([]),[name,setName]=useState(''),[email,setEmail]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/team',{cache:'no-store'}),d=await r.json() as {error?:string;members:Member[]};if(!r.ok)throw Error(d.error);setMembers(d.members)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function save(data:{name:string;email:string;active:boolean;version:number;password?:string}){setBusy(true);try{const r=await fetch('/api/team',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);if(!data.version){setName('');setEmail('');setPassword('')}setResetEmail('');setResetPassword('');toast.success(data.active?'Acesso autorizado.':'Acesso bloqueado.');await load()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 function submit(e:FormEvent){e.preventDefault();void save({name,email,active:true,version:0,...(localMode?{password}:{})})}
 return <section className="lines-panel team-panel"><h2>Equipe e acessos</h2><p>Operadores podem cadastrar, editar e consultar o histórico. Somente você gerencia os acessos.</p><form onSubmit={submit}><label>Nome<Input aria-label="Nome do operador" required maxLength={200} value={name} onChange={e=>setName(e.target.value)}/></label><label>{localMode?'E-mail':'E-mail usado no ChatGPT'}<Input aria-label="E-mail do operador" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><>{localMode&&<label>Senha inicial<Input aria-label="Senha inicial do operador" type="password" autoComplete="new-password" minLength={12} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)}/></label>}</><Button className="action-primary" disabled={busy||loading} type="submit">Autorizar operador</Button></form><>{localMode?<p className="registration-notice">Cada operador entra com o e-mail e a senha cadastrados aqui. A senha pode ser alterada em Configurações → Minha senha.</p>:<p className="registration-notice">Depois de autorizar, libere o mesmo e-mail em <strong>Compartilhar</strong> deste site, como visitante. Cada pessoa entra com sua própria conta do ChatGPT. Esta tela não envia convites.</p>}</>{loading&&<p role="status">Carregando equipe...</p>}{error&&<p role="alert">{error}<Button variant="outline" onClick={()=>void load()}>Tentar novamente</Button></p>}<ul className="team-list">{members.map(m=><li key={m.email}><div><strong>{m.name}</strong><span>{m.email}</span></div><span>{m.is_owner?'Administrador':!m.active?'Bloqueado':m.joined?'Operador':'Aguardando primeiro acesso'}</span>{!m.is_owner&&<Button variant="outline" disabled={busy} onClick={()=>void save({...m,active:!m.active})}>{m.active?'Bloquear':'Reativar'}</Button>}{localMode&&!m.is_owner&&<Button variant="outline" disabled={busy} onClick={()=>{setResetEmail(m.email);setResetPassword('')}}>Redefinir senha</Button>}{resetEmail===m.email&&<form className="operator-password" onSubmit={e=>{e.preventDefault();void save({...m,active:!!m.active,password:resetPassword})}}><Input aria-label="Nova senha do operador" type="password" autoComplete="new-password" required minLength={12} maxLength={128} value={resetPassword} onChange={e=>setResetPassword(e.target.value)}/><Button disabled={busy}>Salvar senha</Button><Button type="button" variant="ghost" onClick={()=>setResetEmail('')}>Cancelar</Button></form>}</li>)}</ul></section>
}
