import {useEffect,useRef,useState,type FormEvent} from 'react';
import {type Config,statusLabels,usageLabels,currency} from '@/lib/atlas';
import {parseCost,deviceSlots} from '@/lib/registration';

type Draft={kind:'line'|'device';action:'create'|'edit';settingsVersion:number;targetId?:string;expectedVersion?:number;fields:Record<string,unknown>};
type Proposal={approvalToken?:string;state:string;questions?:{field:string;question:string}[];error?:string;after?:Record<string,unknown>;changes?:{field:string;before:unknown;after:unknown}[];affectedLineIds?:string[]};
type Item={id:string;name:string;number?:string;model?:string;version?:number};
const labels:Record<string,string>={number:'Número com DDD',name:'Identificação',carrier:'Operadora',usage:'Finalidade',status:'Situação',deviceId:'Aparelho',slot:'Slot ou eSIM',type:'Tipo de aparelho',model:'Modelo',owner:'Responsável',team:'Setor',location:'Localização',cost:'Mensalidade',dataPackage:'Pacote de dados',platform:'Sistema',dueDay:'Dia de vencimento',slots:'Slots disponíveis'};
const lineFields=['name','number','carrier','usage','status','deviceId','slot','owner','team','location','cost','dataPackage'];
const deviceFields=['name','type','model','owner','location'];

export default function AssistantDraft(){
 const [draft,setDraft]=useState<Draft|null>(null),[config,setConfig]=useState<Config|null>(null),[proposal,setProposal]=useState<Proposal|null>(null);
 const [messages,setMessages]=useState<{role:string;text:string}[]>([]),[field,setField]=useState(''),[answer,setAnswer]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [search,setSearch]=useState<'line'|'device'|null>(null),[query,setQuery]=useState(''),[items,setItems]=useState<Item[]>([]),[total,setTotal]=useState(0),[offset,setOffset]=useState(0),[discard,setDiscard]=useState(false);
 const abort=useRef<AbortController|null>(null),end=useRef<HTMLDivElement>(null);
 useEffect(()=>()=>abort.current?.abort(),[]);
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest'});},[messages,proposal]);
 async function api<T=Proposal>(path:string,body?:unknown){
  const r=await fetch(path,{signal:abort.current?.signal,headers:{'Content-Type':'application/json'},...(body?{method:'POST',body:JSON.stringify(body)}:{})});
  const data=await r.json() as T & {error?:string};if(!r.ok)throw Error(data.error||'Não foi possível consultar.');return data;
 }
 async function run(task:()=>Promise<void>){if(busy)return;setBusy(true);setError('');abort.current=new AbortController();try{await task();}catch(e){if(!abort.current.signal.aborted)setError((e as Error).message);}finally{setBusy(false);}}
 function show(p:Proposal){setProposal(p);setField(p.questions?.[0]?.field??'');setAnswer('');setMessages(m=>[...m,{role:'assistant',text:p.questions?.[0]?.question??p.error??(p.state==='unchanged'?'Nenhuma mudança foi proposta.':'Preparei o resumo abaixo. Revise antes de continuar.')}]);}
 async function prepare(next:Draft){setProposal(null);setDraft(next);show(await api('/api/assistant/proposals',next));}
 async function start(kind:'line'|'device'){await run(async()=>{const {config:c}=await api<{config:Config}>('/api/settings');setConfig(c);setMessages([{role:'user',text:kind==='line'?'Preparar nova linha / chip':'Preparar novo aparelho'}]);await prepare({kind,action:'create',settingsVersion:c.version,fields:{}});});}
 async function find(kind:'line'|'device',nextOffset=0){await run(async()=>{setSearch(kind);setDraft(null);setProposal(null);const c=await api<{items:Item[];total:number}>('/api/assistant/catalog?'+new URLSearchParams({kind:kind==='line'?'lines':'devices',query,offset:String(nextOffset)}));setItems(c.items);setTotal(c.total);setOffset(nextOffset);});}
 async function choose(item:Item){await run(async()=>{const {config:c}=await api<{config:Config}>('/api/settings');setConfig(c);const kind=search!;setSearch(null);setMessages([{role:'user',text:'Editar '+item.name}]);const next:Draft={kind,action:'edit',targetId:item.id,expectedVersion:kind==='line'?item.version:c.version,settingsVersion:c.version,fields:{}};setDraft(next);const p=await api('/api/assistant/proposals',next);setProposal(p);setField('name');setAnswer('');setMessages(m=>[...m,{role:'assistant',text:'Qual informação deseja alterar? Selecione o campo e responda abaixo.'}]);});}
 const options=field==='carrier'?config?.carriers.map(x=>[x,x]):field==='status'?Object.entries(statusLabels):field==='usage'?Object.entries(usageLabels):field==='type'?[['iphone','iPhone'],['android','Android']]:field==='deviceId'?[['none','Sem aparelho'],...(config?.devices.map(d=>[d.id,d.name+' · '+d.model])??[])]:field==='slot'?(()=>{const id=draft?.fields.deviceId??proposal?.after?.deviceId;const d=config?.devices.find(d=>d.id===id);return d?deviceSlots(d).map(s=>[s,s==='eSIM'?'eSIM 1':s]):[];})():undefined;
 function display(key:string,value:unknown):string{if(value===null||value===undefined||value==='')return 'Não informado';if(key==='deviceId')return config?.devices.find(d=>d.id===value)?.name??String(value);if(key==='cost')return currency(value as number);if(key==='status')return statusLabels[value as keyof typeof statusLabels];if(key==='usage')return usageLabels[value as keyof typeof usageLabels];if(key==='slot'&&value==='eSIM')return 'eSIM 1';return Array.isArray(value)?value.join(', '):String(value);}
 async function submit(e:FormEvent){e.preventDefault();if(!draft||!field||!answer.trim())return;await run(async()=>{let value:unknown=answer.trim();if(field==='deviceId'&&value==='none')value=null;if(field==='cost')value=parseCost(String(value));const fields={...draft.fields,[field]:value};if(field==='deviceId')fields.slot=null;setMessages(m=>[...m,{role:'user',text:labels[field]+': '+display(field,value)}]);await prepare({...draft,fields});});}
 async function approve(){if(!proposal?.approvalToken||busy||answer.trim())return;const approvalToken=proposal.approvalToken;await run(async()=>{setProposal(null);const result=await api<{saved:boolean}>('/api/assistant/approve',{approvalToken,confirmed:true});if(result.saved){setDraft(null);setField('');setAnswer('');setMessages(m=>[...m,{role:'user',text:'Aprovar e salvar'},{role:'assistant',text:'Cadastro salvo após sua aprovação. Atualize a visão geral para consultar os dados.'}]);}});}
 function reset(){setDraft(null);setProposal(null);setMessages([]);setSearch(null);setItems([]);setField('');setAnswer('');setError('');setDiscard(false);}
 return <div className="assistant-guided">
  <p>Preparação guiada · sem IA conectada. O cadastro só será salvo após sua aprovação. O rascunho permanece ao fechar este painel, mas é descartado ao recarregar ou sair da aplicação. Não digite senhas.</p>
  {!draft&&!search&&<div className="assistant-actions"><button disabled={busy} onClick={()=>start('line')}>Nova linha / chip</button><button disabled={busy} onClick={()=>start('device')}>Novo aparelho</button><button disabled={busy} onClick={()=>find('line')}>Editar linha / chip</button><button disabled={busy} onClick={()=>find('device')}>Editar aparelho</button></div>}
  {search&&<div><form onSubmit={e=>{e.preventDefault();void find(search);}}><label>Buscar cadastro<input value={query} onChange={e=>setQuery(e.target.value)} maxLength={200}/></label><button disabled={busy}>Buscar</button></form><p>{total} resultado(s). Selecione o cadastro correto.</p>{items.map(item=><button disabled={busy} key={item.id} onClick={()=>choose(item)}>{item.name} · {item.number??item.model}</button>)}{offset>0&&<button disabled={busy} onClick={()=>find(search,offset-10)}>Anteriores</button>}{offset+10<total&&<button disabled={busy} onClick={()=>find(search,offset+10)}>Próximos</button>}</div>}
  <div className="assistant-messages" role="log" aria-label="Conversa do rascunho" aria-live="polite">{messages.map((m,i)=><article key={i} className={m.role}><small>{m.role==='user'?'Você':'Atlas · guiado'}</small><p>{m.text}</p></article>)}<div ref={end}/></div>
  {error&&<p role="alert">{error} Seu rascunho foi mantido. Para versões desatualizadas, inicie novamente consultando o cadastro atual.</p>}
  {draft&&<form onSubmit={submit}><label>Campo a informar<select aria-label="Campo a informar" value={field} disabled={busy} onChange={e=>{setField(e.target.value);setAnswer('');}}><option value="">Selecione para ajustar</option>{(draft.kind==='line'?lineFields:deviceFields).map(f=><option key={f} value={f}>{labels[f]}</option>)}</select></label><label>Resposta{options?<select aria-label="Resposta" value={answer} disabled={busy||!field} onChange={e=>setAnswer(e.target.value)}><option value="">Selecione</option>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:<input aria-label="Resposta" value={answer} disabled={busy||!field} onChange={e=>setAnswer(e.target.value)} maxLength={200}/>}</label><button disabled={busy||!field||!answer.trim()}>Enviar resposta</button></form>}
  {busy&&<p role="status">Preparando…</p>}
  {proposal?.state==='ready_for_review'&&<div aria-label="Resumo para revisão" className="assistant-review"><h3>Resumo para revisão</h3>{proposal.changes?.map(change=><div key={change.field}><strong>{labels[change.field]??change.field}</strong>{draft?.action==='edit'&&<p>Antes: {display(change.field,change.before)}</p>}<p>{draft?.action==='edit'?'Depois: ':''}{display(change.field,change.after)}</p></div>)}{!!proposal.affectedLineIds?.length&&<p>Este aparelho está vinculado a {proposal.affectedLineIds.length} linha(s).</p>}<p>Nenhum cadastro foi salvo ainda. Confira os dados antes de aprovar. A revisão vence em dez minutos.</p><button disabled={busy||!!answer.trim()||!proposal.approvalToken} onClick={approve}>Aprovar e salvar</button></div>}
  {(draft||search)&&<button disabled={busy} onClick={()=>setDiscard(true)}>Novo rascunho</button>}
  {discard&&<div role="alert"><p>Descartar este rascunho e começar outro?</p><button disabled={busy} onClick={reset}>Descartar rascunho</button><button onClick={()=>setDiscard(false)}>Continuar editando</button></div>}
 </div>;
}
