import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,readFile,rm,rename,writeFile,readdir,stat} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {createServer} from 'node:net';
import {createHmac,createHash,randomBytes,scryptSync} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
const directory=await mkdtemp(join(tmpdir(),'atlas-access-test-'));let child,logs='';
const reservation=createServer();await new Promise(r=>reservation.listen(0,'127.0.0.1',r));const port=reservation.address().port;await new Promise(r=>reservation.close(r));const base=`http://127.0.0.1:${port}`;
async function start(dir=directory){logs='';child=spawn(process.execPath,['local-dist/server.mjs'],{cwd:resolve('.'),env:{...process.env,ATLAS_DATA_DIR:dir,ATLAS_PORT:String(port)},stdio:['ignore','pipe','pipe']});await new Promise((yes,no)=>{const timer=setTimeout(()=>no(Error('Servidor não iniciou: '+logs)),15000);child.stderr.on('data',d=>logs+=d);child.stdout.on('data',d=>{logs+=d;if(logs.includes('Atlas Linhas disponível')){clearTimeout(timer);yes()}});child.once('exit',()=>{clearTimeout(timer);no(Error('Servidor encerrou: '+logs))})})}
async function stop(){if(child&&child.exitCode===null)await new Promise(r=>{child.once('exit',r);child.kill('SIGTERM')})}
async function req(path,cookie,body,status=200){const r=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{...(cookie?{Cookie:cookie}:{}),...(body===undefined?{}:{Origin:base,'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})});const text=await r.text();assert.equal(r.status,status,`${path} (${body?.action||''}): ${text}`);return {data:JSON.parse(text),text,cookie:r.headers.get('set-cookie')?.split(';')[0]}}
const adminPass='01234567',secret='Atlas-SECRET-ficticio-9283!',codes='RECUPERACAO-TESTE-8425';let admin,operator,opid,google,mail,config,line;
const policy={visibility:'team',viewers:[],revealUsers:[],editUsers:[],quickAccess:false,sensitive:true};
const destination=(id,fields)=>({id,lineId:null,deviceId:null,accountId:null,personId:null,description:'',state:'available',...fields});
const data=(label,login,methods=[],kind='service')=>({service:label.split(' · ')[0],label,login,kind,ownerId:null,sector:'TI',mfa:'enabled',archived:false,methods,checkedAt:null,checkedBy:null});
async function save(a,patch={},extra={}){const {id,version}=a;const d=Object.fromEntries(Object.keys(data('','')).map(k=>[k,a[k]]));return (await req('/api/access',admin,{action:'save',id,version,data:{...d,...patch},...extra})).data.account}
async function unlock(a,cookie=admin,purpose='read',scope='vault',password=adminPass,status=200){return (await req('/api/vault',cookie,{action:'unlock',id:a.id,password,scope,purpose},status)).data}
async function read(a,token,cookie=admin,scope='vault',status=200){return req('/api/vault',cookie,{action:'read',id:a.id,token,scope,field:'password',intent:'reveal'},status)}
try{
 await start();admin=(await req('/api/auth/setup',null,{name:'Admin Teste',email:'admin@example.invalid',password:adminPass},201)).cookie;
 await req('/api/access',null,undefined,401);await req('/api/vault',null,{action:'unlock'},401);
 await req('/api/team',admin,{name:'Ana Teste',email:'ana@example.invalid',password:'00112233',active:true,version:0});operator=(await req('/api/auth/login',null,{email:'ana@example.invalid',password:'00112233'})).cookie;opid=(await req('/api/me',operator)).data.user.id;
 config=(await req('/api/settings',admin)).data.config;config=(await req('/api/settings',admin,{...config,devices:[{id:'iphone',name:'iPhone Teste',type:'iphone',model:'iPhone 15',location:'Diretoria',owner:'Lucas',slots:['Slot 1']},{id:'samsung',name:'Samsung Teste',type:'android',model:'Galaxy',location:'Atendimento',owner:'Ana',slots:['Slot 1']}]})).data.config;
 line=(await req('/api/lines',admin,{number:'51988880101',name:'Linha operacional',carrier:'Vivo',usage:'phone',platform:'',status:'active',deviceId:'iphone',slot:'Slot 1',location:'',owner:'Lucas',team:'TI',cost:1000,dueDay:20,notes:'',version:0})).data.line;
 const legacyId=(await req('/api/backups',admin,{})).data.id,legacy=(await req('/api/backups?id='+legacyId,admin)).data;
 delete legacy.payload.access;legacy.signature=createHmac('sha256',await readFile(join(directory,'backup.key'),'utf8')).update(JSON.stringify(legacy.payload)).digest('hex');
 mail=(await req('/api/access',admin,{action:'save',version:0,data:data('Google · Equipe','equipe@example.invalid',[],'email'),policy:{...policy,quickAccess:true,sensitive:false}},201)).data.account;
 const methods=[{id:'prompt',type:'prompt',purpose:'access',stage:1,preferred:true,instruction:'Confira o aplicativo Google.',destinations:[destination('t1',{deviceId:'iphone'}),destination('t2',{deviceId:'samsung'})]},{id:'sms',type:'sms',purpose:'access',stage:1,preferred:false,instruction:'',destinations:[destination('t3',{lineId:line.id})]},{id:'email',type:'email',purpose:'recovery',stage:1,preferred:false,instruction:'',destinations:[destination('t4',{accountId:mail.id})]}];
 google=(await req('/api/access',admin,{action:'save',version:0,data:data('Google · Direção','direcao@example.invalid',methods,'email'),policy},201)).data.account;
 assert.equal(google.methods[0].destinations.length,2);assert.equal(google.canReveal,true);assert.equal(google.hasSecret,false);
 await req('/api/access',operator,{action:'save',version:0,data:data('Outro','conta'),policy},403);
 await req('/api/access',admin,{action:'save',version:0,data:data('Google · Direção','direcao@example.invalid',methods,'email'),policy},409);
 await req('/api/access',admin,{action:'save',version:0,data:data('Falha','conta',[{...methods[0],destinations:[destination('bad',{deviceId:'ausente'})]}]),policy},400);
 await req('/api/access',admin,{action:'save',id:google.id,version:google.version,data:data('Google · Direção','direcao@example.invalid',[{...methods[2],destinations:[destination('bad',{accountId:google.id})]}],'email'),policy},400);
 const stale=google;google=await save(google,{sector:'Operação'});await req('/api/access',admin,{action:'save',id:stale.id,version:stale.version,data:data('Google · Direção','direcao@example.invalid',methods,'email'),policy},409);
 config=(await req('/api/settings',admin)).data.config;await req('/api/settings',admin,{...config,devices:config.devices.filter(d=>d.id!=='samsung')},409);
 line=(await req('/api/lines',admin,{...line,deviceId:'samsung'})).data.line;const loaded=(await req('/api/access',admin)).data.accounts.find(a=>a.id===google.id);assert.equal(loaded.methods[0].destinations[0].deviceId,'iphone');assert.equal(loaded.methods[1].destinations[0].lineId,line.id);
 await req('/api/access',operator,{action:'report',id:google.id,destinationId:'t1',reason:'Aparelho indisponível'});const report=(await req('/api/access',admin)).data.reports[0];assert.equal(report.status,'open');assert.equal((await req('/api/access',admin)).data.accounts.find(a=>a.id===google.id).methods[0].destinations[0].state,'available');
 await req('/api/access',operator,{action:'resolve',id:report.id},403);await req('/api/access',admin,{action:'resolve',id:report.id});
 await unlock(google,admin,'read','quick',adminPass,403);await unlock(google,operator,'read','vault','00112233',403);await unlock(google,admin,'write','vault','errada',403);
 let key=await unlock(google,admin,'write');await req('/api/vault',admin,{action:'write',id:google.id,scope:'vault',token:key.token,secret:{password:secret,recoveryCodes:codes}});
 google=(await req('/api/access',admin)).data.accounts.find(a=>a.id===google.id);
 assert.equal(google.hasSecret,true);assert.equal('secret' in google,false);key=await unlock(google);assert.equal((await read(google,key.token)).data.value,secret);
 await read(google,key.token,operator,'vault',403);await read(google,key.token,admin,'quick',403);await read(google,'0'.repeat(64),admin,'vault',403);
 const anotherSession=(await req('/api/auth/login',null,{email:'admin@example.invalid',password:adminPass})).cookie;await read(google,key.token,anotherSession,'vault',403);
 const beforeUpdate=key;google=await save(google,{}, {policy:{...policy,revealUsers:[opid]}});await read(google,beforeUpdate.token,admin,'vault',403);
 let operatorKey=await unlock(google,operator,'read','vault','00112233');assert.equal((await read(google,operatorKey.token,operator)).data.value,secret);
 const backupId=(await req('/api/backups',admin,{})).data.id,backup=(await req('/api/backups?id='+backupId,admin)).data;assert.equal(backup.payload.access.accounts.length,2);assert.ok(!JSON.stringify(backup).includes(secret));assert.ok(!JSON.stringify(backup).includes(codes));assert.equal('vaultKey' in backup.payload.access,false);
 google=await save(google,{}, {policy:{...policy,revealUsers:[]}});await read(google,operatorKey.token,operator,'vault',403);
 let preview=(await req('/api/restore',admin,{mode:'preview',file:backup})).data;google=await save(google,{sector:'Depois da análise'});await req('/api/restore',admin,{mode:'restore',file:backup,token:preview.token},409);
 preview=(await req('/api/restore',admin,{mode:'preview',file:backup})).data;await req('/api/restore',admin,{mode:'restore',file:backup,token:preview.token});google=(await req('/api/access',admin)).data.accounts.find(a=>a.id===google.id);assert.equal(google.canReveal,true);assert.equal(google.policy.revealUsers.length,0);await unlock(google,operator,'read','vault','00112233',403);key=await unlock(google);assert.equal((await read(google,key.token)).data.value,secret);
 // Legacy backup retains the new module, validating links against the incoming inventory.
 preview=(await req('/api/restore',admin,{mode:'preview',file:legacy})).data;assert.equal(preview.summary.accessMode,'preserve');await req('/api/restore',admin,{mode:'restore',file:legacy,token:preview.token});assert.equal((await req('/api/access',admin)).data.accounts.length,2);
 google=(await req('/api/access',admin)).data.accounts.find(a=>a.id===google.id);key=await unlock(google,admin,'write');await req('/api/vault',admin,{action:'write',id:google.id,scope:'vault',token:key.token,secret:{password:secret+'-nova'}});google=(await req('/api/access',admin)).data.accounts.find(a=>a.id===google.id);key=await unlock(google);assert.equal((await req('/api/vault',admin,{action:'read',id:google.id,token:key.token,scope:'vault',field:'recoveryCodes',intent:'reveal'})).data.value,codes);
 const db=new DatabaseSync(join(directory,'atlas-linhas.sqlite'));db.prepare('UPDATE access_unlocks SET expires_at=0').run();db.close();await read(google,key.token,admin,'vault',403);
 google=await save(google,{}, {policy:{...policy,visibility:'selected'}});assert.ok(!(await req('/api/access',operator)).data.accounts.some(a=>a.id===google.id));await req('/api/access?history='+google.id,operator,undefined,404);
 await stop();await start();key=await unlock(google);assert.equal((await read(google,key.token)).data.value,secret+'-nova');
 await rename(join(directory,'vault.key'),join(directory,'vault.key.saved'));await read(google,key.token,admin,'vault',503);assert.ok(!(await readdir(directory)).includes('vault.key'));await rename(join(directory,'vault.key.saved'),join(directory,'vault.key'));
 assert.equal((await read(google,key.token)).data.value,secret+'-nova');const hist=await req('/api/access?history='+google.id,admin);assert.ok(!hist.text.includes(secret));assert.ok(!hist.text.includes(codes));
 await stop();for(const name of ['atlas-linhas.sqlite','atlas-linhas.sqlite-wal'])try{const raw=await readFile(join(directory,name));assert.ok(!raw.includes(Buffer.from(secret)));assert.ok(!raw.includes(Buffer.from(codes)))}catch(e){if(e.code!=='ENOENT')throw e}
 const check=new DatabaseSync(join(directory,'atlas-linhas.sqlite'));assert.equal(check.prepare('PRAGMA integrity_check').get().integrity_check,'ok');assert.equal(check.prepare('PRAGMA foreign_key_check').all().length,0);check.close();
 console.log('PASS: contas e múltiplos destinos, vínculos existentes, conflitos, permissões, credenciais criptografadas, desbloqueio por sessão, revogação, expiração, histórico sem segredos, backups novo/antigo, restauração sem ampliar acesso e chave ausente.');
 // Upgrade fixture: baseline database with an existing login. All data remains fictitious.
 const oldDir=await mkdtemp(join(tmpdir(),'atlas-access-upgrade-'));
 try{const old=new DatabaseSync(join(oldDir,'atlas-linhas.sqlite'));old.exec('PRAGMA foreign_keys=ON; CREATE TABLE local_migrations(name TEXT PRIMARY KEY,checksum TEXT NOT NULL)');const files=(await readdir('drizzle')).filter(n=>/^\d+.*\.sql$/.test(n)).sort().map(n=>[n,join('drizzle',n)]);files.push(['local-auth-v1','local/server/schema.sql']);for(const [name,path]of files){const sql=await readFile(path,'utf8');old.exec(sql);old.prepare('INSERT INTO local_migrations VALUES(?,?)').run(name,createHash('sha256').update(sql).digest('hex'))}old.prepare("INSERT INTO storage_revision VALUES('main',0)").run();old.prepare("INSERT INTO members VALUES('old@example.invalid','old-user','Original','admin',1,1,1,?)").run(new Date().toISOString());const salt=randomBytes(16).toString('hex');old.prepare('INSERT INTO local_credentials VALUES(?,?)').run('old-user','scrypt:'+salt+':'+scryptSync(adminPass,salt,64).toString('hex'));old.close();const backupKey=randomBytes(32).toString('hex');await writeFile(join(oldDir,'backup.key'),backupKey,{mode:0o600});await start(oldDir);const login=await req('/api/auth/login',null,{email:'old@example.invalid',password:adminPass});assert.ok(login.cookie);await stop();const checkpoints=await readdir(join(oldDir,'checkpoints'));assert.equal(checkpoints.length,1);const checkpoint=join(oldDir,'checkpoints',checkpoints[0]);assert.equal(await readFile(join(checkpoint,'backup.key'),'utf8'),backupKey);const before=new DatabaseSync(join(checkpoint,'atlas-linhas.sqlite'));assert.equal(before.prepare('SELECT count(*) n FROM local_migrations').get().n,4);assert.equal(before.prepare('SELECT count(*) n FROM local_credentials').get().n,1);assert.equal(before.prepare("SELECT count(*) n FROM sqlite_master WHERE name='access_accounts'").get().n,0);before.close();assert.equal((await stat(join(checkpoint,'atlas-linhas.sqlite'))).mode&0o777,0o600);await start(oldDir);await stop();assert.equal((await readdir(join(oldDir,'checkpoints'))).length,1);console.log('PASS: migração adicional, checkpoint anterior completo, login preservado e migração aplicada uma única vez.');}finally{await stop();await rm(oldDir,{recursive:true,force:true})}
}finally{await stop();await rm(directory,{recursive:true,force:true})}
