import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {sqlite} from './environment';
import {requireActor,AccessError,type Actor} from '@/lib/access';
import {methodLabels,accountDataSchema,accountPolicySchema,defaultPolicy,type AccessAccount,type AccountData,type AccountPolicy,type AccessPerson,type AccessReport,type AccessEvent} from '@/lib/accounts';
import {defaultConfig,type Config,type Line} from '@/lib/atlas';
export type AccountRow={id:string;account_key:string;data:string;policy:string;version:number;secret:string|null;secret_version:number;created_at:string;updated_at:string};
export const stamp=()=>new Date().toISOString();
export function transaction<T>(run:()=>T):T{sqlite.exec('BEGIN IMMEDIATE');try{const result=run();sqlite.exec('COMMIT');return result}catch(e){sqlite.exec('ROLLBACK');throw e}}
export function allRows(){return sqlite.prepare('SELECT * FROM access_accounts ORDER BY updated_at DESC,id').all() as unknown as AccountRow[]}
export function findRow(id:string){const row=sqlite.prepare('SELECT * FROM access_accounts WHERE id=?').get(id) as unknown as AccountRow|undefined;if(!row)throw new AccessError('Conta não encontrada.',404);return row}
export function policyOf(row:AccountRow){return JSON.parse(row.policy) as AccountPolicy}
export function canView(actor:Actor,policy:AccountPolicy){return actor.role==='admin'||policy.visibility==='team'||policy.viewers.includes(actor.id)||policy.revealUsers.includes(actor.id)||policy.editUsers.includes(actor.id)}
export function canReveal(actor:Actor,policy:AccountPolicy){return actor.role==='admin'||policy.revealUsers.includes(actor.id)}
export function canEdit(actor:Actor,policy:AccountPolicy){return actor.role==='admin'||policy.editUsers.includes(actor.id)}
export function authorizedRow(actor:Actor,id:string,operation:'view'|'reveal'|'edit'='view'){
 const row=findRow(id),policy=policyOf(row);if(!canView(actor,policy))throw new AccessError('Conta não encontrada ou acesso não autorizado.',404);
 if(operation==='reveal'&&!canReveal(actor,policy)||operation==='edit'&&!canEdit(actor,policy))throw new AccessError('Seu usuário não tem permissão para esta credencial.',403);return row;
}
export function publicRow(row:AccountRow,actor:Actor):AccessAccount{const p=policyOf(row);return {...JSON.parse(row.data),id:row.id,version:row.version,credentialVersion:row.secret_version,hasSecret:!!row.secret,canReveal:canReveal(actor,p),canEdit:canEdit(actor,p),quickAccess:p.quickAccess,sensitive:p.sensitive,...(actor.role==='admin'?{policy:p}:{})}}
export function people():AccessPerson[]{const users=sqlite.prepare('SELECT user_id,name FROM members WHERE user_id IS NOT NULL').all();const saved=sqlite.prepare('SELECT id,name FROM access_people ORDER BY name').all();return [...users.map(u=>({id:'member:'+u.user_id,name:String(u.name),userId:String(u.user_id)})),...saved.map(p=>({id:String(p.id),name:String(p.name),userId:null}))]}
export function inventory(){const c=sqlite.prepare("SELECT data,version FROM settings WHERE id='main'").get();return {config:c?{...JSON.parse(String(c.data)),version:Number(c.version)} as Config:defaultConfig,lines:sqlite.prepare('SELECT id,data,version FROM lines').all().map(l=>({...JSON.parse(String(l.data)),id:l.id,version:l.version})) as Line[]}}
export function audit(actor:Actor,accountId:string|null,action:string,detail:Record<string,unknown>={}){sqlite.prepare('INSERT INTO access_history VALUES(?,?,?,?,?,?)').run(randomUUID(),accountId,action,stamp(),actor.name,JSON.stringify({...detail,actorId:actor.id}))}
export function reportRows():AccessReport[]{return sqlite.prepare('SELECT * FROM access_reports ORDER BY created_at DESC').all().map(r=>({id:String(r.id),accountId:String(r.account_id),destinationId:r.destination_id as string|null,reason:String(r.reason),status:r.status as 'open'|'resolved',createdAt:String(r.created_at),author:String(r.author),resolvedAt:r.resolved_at as string|null,resolvedBy:r.resolved_by as string|null}))}
export function validateData(data:AccountData,id:string,others:{id:string;data:AccountData}[],config:Config,lines:Line[],personIds:Set<string>){
 if(data.kind==='email'&&!z.string().email().safeParse(data.login).success)throw new AccessError('Informe um endereço válido para a caixa de e-mail.',400);
 if(data.ownerId&&!personIds.has(data.ownerId))throw new AccessError('Responsável não encontrado.',400);
 const ids=new Set<string>(),preferred=new Set<number>();
 for(const m of data.methods){if(ids.has(m.id))throw new AccessError('Métodos duplicados.',400);ids.add(m.id);if(m.preferred&&m.purpose!=='recovery'){if(preferred.has(m.stage))throw new AccessError('Escolha apenas um método preferencial por etapa.',400);preferred.add(m.stage)}
  const refs=new Set<string>();for(const t of m.destinations){if(ids.has(t.id))throw new AccessError('Destinos duplicados.',400);ids.add(t.id);
   if(t.personId&&!personIds.has(t.personId))throw new AccessError('Responsável pelo destino não encontrado.',400);
   if(t.lineId&&!lines.some(l=>l.id===t.lineId)||t.deviceId&&!config.devices.some(d=>d.id===t.deviceId))throw new AccessError('Linha ou aparelho não encontrado. Recarregue os cadastros.',400);
   const email=others.find(a=>a.id===t.accountId);if(t.accountId&&(t.accountId===id||!email||email.data.kind!=='email'))throw new AccessError('Vincule outra caixa de e-mail cadastrada. A conta não pode recuperar a si mesma.',400);
   const count=[t.lineId,t.deviceId,t.accountId].filter(Boolean).length;if(count>1)throw new AccessError('Cada destino deve apontar para um único cadastro.',400);
   if(['sms','call'].includes(m.type)&&(!t.lineId||count!==1))throw new AccessError('Selecione uma linha existente para SMS ou ligação.',400);
   if(m.type==='email'&&(!t.accountId||count!==1))throw new AccessError('Selecione uma caixa de e-mail cadastrada.',400);
   if(['authenticator','prompt'].includes(m.type)&&(!t.deviceId||count!==1))throw new AccessError('Selecione um aparelho para cada destino.',400);
   if(['key','recovery','other'].includes(m.type)&&(count||!t.description))throw new AccessError('Informe a identificação ou localização deste método, sem segredos.',400);
   if(m.type==='passkey'&&(t.lineId||t.accountId||(!t.deviceId&&!t.description)))throw new AccessError('Indique o aparelho ou a localização da passkey.',400);
   if(m.type==='recovery'&&m.purpose!=='recovery')throw new AccessError('Códigos de recuperação devem ter finalidade de recuperação.',400);
   const ref=t.lineId||t.deviceId||t.accountId||t.description.toLowerCase();if(refs.has(ref))throw new AccessError('O mesmo destino aparece duas vezes neste método.',400);refs.add(ref);
  }
 }
}
function validatePolicy(policy:AccountPolicy){const ids=new Set(sqlite.prepare('SELECT user_id FROM members WHERE user_id IS NOT NULL').all().map(u=>String(u.user_id)));for(const id of [...policy.viewers,...policy.revealUsers,...policy.editUsers])if(!ids.has(id))throw new AccessError('Usuário de acesso não encontrado.',400)}
export async function accessGET(req:Request){const actor=await requireActor(),url=new URL(req.url),historyId=url.searchParams.get('history');
 if(historyId){authorizedRow(actor,historyId);const rows=sqlite.prepare('SELECT * FROM access_history WHERE account_id=? ORDER BY created_at DESC,rowid DESC LIMIT 200').all(historyId);return Response.json({history:rows.map(r=>({id:r.id,accountId:r.account_id,action:r.action,createdAt:r.created_at,actor:r.actor,detail:JSON.parse(String(r.detail))})) as AccessEvent[]})}
 const rows=allRows().filter(r=>canView(actor,policyOf(r))),ids=new Set(rows.map(r=>r.id));return Response.json({accounts:rows.map(r=>publicRow(r,actor)),people:people(),users:actor.role==='admin'?sqlite.prepare('SELECT user_id AS id,name,active FROM members WHERE user_id IS NOT NULL ORDER BY name').all().map(u=>({...u,active:!!u.active})):[],canManage:actor.role==='admin',reports:reportRows().filter(r=>ids.has(r.accountId))});
}
const saveSchema=z.object({action:z.literal('save'),id:z.string().max(100).optional(),version:z.number().int().nonnegative(),data:accountDataSchema,policy:accountPolicySchema.optional()}).strict();
export async function accessPOST(req:Request){const actor=await requireActor(),input=z.object({action:z.string()}).passthrough().parse(await req.json());
 if(input.action==='person'){if(actor.role!=='admin')throw new AccessError('Somente o administrador cadastra responsáveis.',403);const d=z.object({action:z.literal('person'),name:z.string().trim().min(1).max(200)}).strict().parse(input);const existing=people().find(p=>p.name.toLowerCase()===d.name.toLowerCase());if(existing)return Response.json({person:existing});const person={id:randomUUID(),name:d.name,userId:null};transaction(()=>{sqlite.prepare('INSERT INTO access_people VALUES(?,?)').run(person.id,person.name);audit(actor,null,'person-created',{personId:person.id})});return Response.json({person}, {status:201})}
 if(input.action==='report'){const d=z.object({action:z.literal('report'),id:z.string().max(100),destinationId:z.string().max(100).nullable(),reason:z.string().trim().min(1).max(1000)}).strict().parse(input);const row=authorizedRow(actor,d.id),data=JSON.parse(row.data) as AccountData;if(d.destinationId&&!data.methods.some(m=>m.destinations.some(t=>t.id===d.destinationId)))throw new AccessError('Destino não encontrado.',400);transaction(()=>{sqlite.prepare('INSERT INTO access_reports VALUES(?,?,?,?,?,?,?,?,?)').run(randomUUID(),row.id,d.destinationId,d.reason,'open',stamp(),actor.name,null,null);audit(actor,row.id,'problem-reported',{destinationId:d.destinationId,reason:d.reason})});return Response.json({ok:true})}
 if(input.action==='resolve'){const d=z.object({action:z.literal('resolve'),id:z.string().max(100)}).strict().parse(input);const report=sqlite.prepare('SELECT account_id FROM access_reports WHERE id=?').get(d.id);if(!report)throw new AccessError('Pendência não encontrada.',404);authorizedRow(actor,String(report.account_id),'edit');transaction(()=>{const r=sqlite.prepare("UPDATE access_reports SET status='resolved',resolved_at=?,resolved_by=? WHERE id=? AND status='open'").run(stamp(),actor.name,d.id);if(!r.changes)throw new AccessError('A pendência já foi resolvida.',409);audit(actor,String(report.account_id),'problem-resolved',{reportId:d.id})});return Response.json({ok:true})}
 if(input.action==='check'){const d=z.object({action:z.literal('check'),id:z.string().max(100),version:z.number().int().positive()}).strict().parse(input);return transaction(()=>{const row=authorizedRow(actor,d.id,'edit');if(row.version!==d.version)throw new AccessError('O cadastro mudou. Recarregue antes de conferir.',409);const data={...JSON.parse(row.data),checkedAt:stamp(),checkedBy:actor.id};sqlite.prepare('UPDATE access_accounts SET data=?,version=version+1,updated_at=? WHERE id=?').run(JSON.stringify(data),stamp(),row.id);audit(actor,row.id,'checked');return Response.json({account:publicRow(findRow(row.id),actor)})})}
 const d=saveSchema.parse(input);return transaction(()=>{const previous=d.id?authorizedRow(actor,d.id,'edit'):undefined;if(!previous&&actor.role!=='admin')throw new AccessError('Somente o administrador cria contas.',403);if(previous&&previous.version!==d.version||!previous&&d.version!==0)throw new AccessError('O cadastro mudou. Recarregue antes de salvar.',409);
 const id=previous?.id||randomUUID(),policy=previous?policyOf(previous):defaultPolicy;if(d.policy&&actor.role!=='admin')throw new AccessError('Somente o administrador pode alterar permissões.',403);const nextPolicy=d.policy||policy;validatePolicy(nextPolicy);
 const data={...d.data,checkedAt:previous?JSON.parse(previous.data).checkedAt:null,checkedBy:previous?JSON.parse(previous.data).checkedBy:null};
 const {config,lines}=inventory();validateData(data,id,allRows().map(r=>({id:r.id,data:JSON.parse(r.data)})),config,lines,new Set(people().map(p=>p.id)));
 if(previous&&JSON.parse(previous.data).kind==='email'&&data.kind!=='email'&&allRows().some(r=>(JSON.parse(r.data) as AccountData).methods.some(m=>m.destinations.some(t=>t.accountId===id))))throw new AccessError('Esta caixa de e-mail está vinculada a outras contas.',409);
 if(previous&&JSON.stringify(data)===previous.data&&JSON.stringify(nextPolicy)===previous.policy)return Response.json({account:publicRow(previous,actor)});
 // Editing the map requires a new manual confirmation. No service is checked automatically.
 data.checkedAt=null;data.checkedBy=null;const now=stamp(),key=[data.service,data.login].map(v=>v.trim().toLowerCase()).join('|');
 try{if(previous)sqlite.prepare('UPDATE access_accounts SET account_key=?,data=?,policy=?,version=version+1,updated_at=? WHERE id=?').run(key,JSON.stringify(data),JSON.stringify(nextPolicy),now,id);else sqlite.prepare('INSERT INTO access_accounts(id,account_key,data,policy,version,created_at,updated_at) VALUES(?,?,?,?,1,?,?)').run(id,key,JSON.stringify(data),JSON.stringify(nextPolicy),now,now)}catch(e){if(String(e).includes('UNIQUE'))throw new AccessError('Este serviço e login já estão cadastrados.',409);throw e}
 const personLabel=(id:string|null)=>people().find(p=>p.id===id)?.name||'Não informado';
 const values=(d:AccountData)=>({'Serviço':d.service,'Nome da conta':d.label,'Login':d.login,'Responsável':personLabel(d.ownerId),'Setor':d.sector,'2FA':d.mfa,'Situação':d.archived?'Arquivada':'Ativa','Métodos':d.methods.map(m=>methodLabels[m.type]+' · '+m.purpose+' · etapa '+m.stage+' · '+m.destinations.map(t=>(lines.find(l=>l.id===t.lineId)?.number||config.devices.find(v=>v.id===t.deviceId)?.name||othersLabel(t.accountId)||t.description)+' / '+t.state+' / '+personLabel(t.personId)).join(', ')+' · '+m.instruction+(m.preferred?' · preferencial':'')).join('; ')});
 function othersLabel(id:string|null){return id?'Caixa de e-mail vinculada':''}
 const before=previous?values(JSON.parse(previous.data)):null,after=values(data),changes=Object.entries(after).filter(([k,v])=>!before||before[k as keyof typeof before]!==v).map(([field,to])=>({field,before:before?.[field as keyof typeof before]||'Não informado',after:to||'Não informado'}));
 audit(actor,id,previous?'account-updated':'account-created',{changes,policyChanged:!previous||previous.policy!==JSON.stringify(nextPolicy)});return Response.json({account:publicRow(findRow(id),actor)},{status:previous?200:201});});
}
